import type { GitOperation, RebasePlanEntry } from "../../shared/contracts/model";

export const FIXTURE_OID = "1".repeat(40);
export const OTHER_FIXTURE_OID = "2".repeat(40);

export const FIXTURE_REBASE_ENTRY: RebasePlanEntry = {
  oid: FIXTURE_OID,
  subject: "subject",
  parents: [],
  action: "pick",
  message: null,
  published: false,
  mergeCommit: false,
};

export const VALID_GIT_OPERATIONS = [
  { kind: "stage", paths: ["file"] },
  { kind: "stageAll" },
  { kind: "stageTracked" },
  { kind: "addIntent", paths: ["file"] },
  { kind: "unstage", paths: ["file"] },
  { kind: "removeCached", paths: ["file"] },
  { kind: "discard", paths: ["file"] },
  { kind: "applyPatch", patch: "diff --git", cached: false, reverse: false },
  { kind: "partialPatch", patch: "@@", cached: true, reverse: true },
  {
    kind: "commit",
    message: "message",
    amend: false,
    signOff: false,
    gpgSign: false,
  },
  {
    kind: "commitAdvanced",
    message: "message",
    amend: true,
    signOff: true,
    gpgSign: true,
    skipHooks: true,
    commitAll: true,
  },
  { kind: "fetch", remote: "origin", prune: true },
  { kind: "pull", rebase: true },
  {
    kind: "push",
    destination: {
      remote: "origin",
      remoteRef: "refs/heads/main",
      localRevision: "HEAD",
      setUpstream: true,
    },
    mode: { kind: "forceWithLease", expectedRemoteOid: FIXTURE_OID },
  },
  {
    kind: "createBranch",
    name: "feature",
    startPoint: "HEAD",
    checkout: true,
  },
  { kind: "renameBranch", oldName: "old", newName: "new" },
  { kind: "deleteBranch", name: "old", force: true },
  { kind: "setUpstream", branch: "main", upstream: "origin/main" },
  { kind: "deleteRemoteBranch", remote: "origin", branch: "feature" },
  { kind: "checkout", target: "main", force: true },
  { kind: "createTag", name: "v1", revision: "HEAD", message: "release" },
  { kind: "deleteTag", name: "v1" },
  { kind: "pushTag", remote: "origin", name: "v1" },
  { kind: "reset", revision: "HEAD^", mode: "mixed" },
  { kind: "revert", revisions: [FIXTURE_OID], noCommit: true },
  { kind: "cherryPick", revisions: [FIXTURE_OID], noCommit: false },
  { kind: "merge", revision: "feature", noFf: true, squash: false },
  { kind: "rebase", onto: "main", branch: "feature" },
  {
    kind: "interactiveRebase",
    base: "HEAD^",
    entries: [FIXTURE_REBASE_ENTRY],
    options: { autostash: true, updateRefs: true, preserveMerges: true },
  },
  { kind: "dropCommits", revisions: [FIXTURE_OID] },
  { kind: "squashCommits", revisions: [OTHER_FIXTURE_OID, FIXTURE_OID] },
  { kind: "rewordCommit", revision: FIXTURE_OID, message: "new message" },
  { kind: "undoCommit" },
  { kind: "createFixupCommit", revision: FIXTURE_OID },
  { kind: "createSquashCommit", revision: FIXTURE_OID },
  { kind: "continue", operation: "rebase" },
  { kind: "skip", operation: "cherryPick" },
  { kind: "abort", operation: "merge" },
  {
    kind: "stashPush",
    message: "save",
    includeUntracked: true,
    keepIndex: true,
  },
  { kind: "stashApply", stash: "stash@{0}", pop: true, reinstateIndex: true },
  { kind: "stashDrop", stash: "stash@{0}" },
  { kind: "stashClear" },
  { kind: "stashBranch", stash: "stash@{0}", branch: "from-stash" },
  { kind: "unshallow" },
  { kind: "updateSubmodules", init: true, recursive: true },
  { kind: "setConfig", key: "user.name", value: "Person" },
  {
    kind: "worktreeAdd",
    path: "/tmp/worktree",
    branch: "work",
    startPoint: "HEAD",
  },
  { kind: "worktreeRemove", path: "/tmp/worktree", force: true },
  {
    kind: "remoteAdd",
    name: "upstream",
    url: "https://example.invalid/repo.git",
  },
  { kind: "remoteRemove", name: "upstream" },
  {
    kind: "remoteSetUrl",
    name: "origin",
    url: "ssh://example.invalid/repo.git",
  },
] satisfies readonly GitOperation[];
