
/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_nesconsole_free: (a: number, b: number) => void;
export const nesconsole_new: (a: number, b: number) => [number, number, number];
export const nesconsole_run_frame: (a: number) => void;
export const nesconsole_frame: (a: number) => [number, number];
export const nesconsole_set_button: (a: number, b: number, c: number) => void;
export const nesconsole_audio: (a: number) => [number, number];
export const nesconsole_chr: (a: number) => [number, number];
export const nesconsole_palette_ram: (a: number) => [number, number];
export const ntsc_color: (a: number) => [number, number];
export const decode_tile: (a: number, b: number) => [number, number];
export const __wbg_snakeconsole_free: (a: number, b: number) => void;
export const snakeconsole_new: (a: number) => number;
export const snakeconsole_set_key: (a: number, b: number) => void;
export const snakeconsole_run: (a: number, b: number) => number;
export const snakeconsole_game_over: (a: number) => number;
export const snakeconsole_snake_len: (a: number) => number;
export const snakeconsole_frame: (a: number) => [number, number];
export const __wbg_cpuinspector_free: (a: number, b: number) => void;
export const cpuinspector_new: () => number;
export const cpuinspector_load: (a: number, b: number, c: number, d: number) => void;
export const cpuinspector_step: (a: number) => number;
export const cpuinspector_read: (a: number, b: number) => number;
export const cpuinspector_write: (a: number, b: number, c: number) => void;
export const cpuinspector_disasm_at: (a: number, b: number) => [number, number];
export const cpuinspector_a: (a: number) => number;
export const cpuinspector_x: (a: number) => number;
export const cpuinspector_y: (a: number) => number;
export const cpuinspector_sp: (a: number) => number;
export const cpuinspector_pc: (a: number) => number;
export const cpuinspector_p: (a: number) => number;
export const cpuinspector_cycles: (a: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
