export const designSystem = {
  version: "alpha",
  name: "Vercel Analysis",
  colors: {
    primary: "#171717",
    onPrimary: "#ffffff",
    ink: "#171717",
    body: "#4d4d4d",
    mute: "#8f8f8f",
    faint: "#a1a1a1",
    hairline: "#ebebeb",
    hairlineSoft: "#f2f2f2",
    canvas: "#fafafa",
    canvasElevated: "#ffffff",
    link: "#0070f3",
    linkDeep: "#0761d1",
    linkSoft: "#d3e5ff",
    error: "#ee0000",
    errorDeep: "#c50000",
    warning: "#f5a623",
    warningSoft: "#ffefcf",
    warningDeep: "#ab570a",
    violet: "#7928ca",
    violetSoft: "#d8ccf1",
    cyan: "#50e3c2",
    cyanSoft: "#aaffec",
    pink: "#ff0080",
    magenta: "#eb367f",
    gradientDevelopStart: "#007cf0",
    gradientDevelopEnd: "#00dfd8",
    gradientPreviewStart: "#7928ca",
    gradientPreviewEnd: "#ff0080",
    gradientShipStart: "#ff4d4d",
    gradientShipEnd: "#f9cb28",
  },
  typography: {
    displayXl: {
      fontFamily: "Geist, Arial, sans-serif",
      fontSize: "48px",
      fontWeight: 600,
      lineHeight: "48px",
      letterSpacing: "0",
    },
    headingLg: {
      fontFamily: "Geist, Arial, sans-serif",
      fontSize: "32px",
      fontWeight: 600,
      lineHeight: "40px",
      letterSpacing: "0",
    },
    headingMd: {
      fontFamily: "Geist, Arial, sans-serif",
      fontSize: "20px",
      fontWeight: 600,
      lineHeight: "28px",
      letterSpacing: "0",
    },
    labelSm: {
      fontFamily: "Geist, Arial, sans-serif",
      fontSize: "14px",
      fontWeight: 500,
      lineHeight: "20px",
      letterSpacing: "0",
    },
    monoEyebrow: {
      fontFamily: "Geist Mono, ui-monospace, SFMono-Regular, Menlo, monospace",
      fontSize: "12px",
      fontWeight: 500,
      lineHeight: "16px",
      letterSpacing: "0",
    },
    bodyLg: {
      fontFamily: "Geist, Arial, sans-serif",
      fontSize: "16px",
      fontWeight: 400,
      lineHeight: "24px",
      letterSpacing: "0",
    },
    bodyMd: {
      fontFamily: "Geist, Arial, sans-serif",
      fontSize: "14px",
      fontWeight: 400,
      lineHeight: "20px",
      letterSpacing: "0",
    },
    bodySm: {
      fontFamily: "Geist, Arial, sans-serif",
      fontSize: "12px",
      fontWeight: 400,
      lineHeight: "16px",
      letterSpacing: "0",
    },
    buttonLg: {
      fontFamily: "Geist, Arial, sans-serif",
      fontSize: "16px",
      fontWeight: 500,
      lineHeight: "20px",
      letterSpacing: "0",
    },
    buttonMd: {
      fontFamily: "Geist, Arial, sans-serif",
      fontSize: "14px",
      fontWeight: 500,
      lineHeight: "20px",
      letterSpacing: "0",
    },
    code: {
      fontFamily: "Geist Mono, ui-monospace, SFMono-Regular, Menlo, monospace",
      fontSize: "14px",
      fontWeight: 400,
      lineHeight: "20px",
      letterSpacing: "0",
    },
  },
  rounded: {
    none: "0",
    sm: "6px",
    md: "12px",
    lg: "16px",
    pillCategory: "64px",
    pill: "100px",
    full: "9999px",
  },
  spacing: {
    xxs: "4px",
    xs: "8px",
    sm: "12px",
    md: "16px",
    lg: "24px",
    xl: "32px",
    "2xl": "40px",
    "3xl": "64px",
    "4xl": "96px",
    section: "128px",
  },
} as const;

export type DesignSystem = typeof designSystem;
