import {
  type CaptionDisplayPreferences,
  type LocalTranslationFetch,
  type LocalTranslationRepository,
  LocalTranslationService,
  type LocalTranslationSettings,
  type RunTranslationJobOptions,
  type TranslationInput,
  type TranslationJobResult,
  type TranslationOutput,
} from "./local-translation";

export interface CaptionLanguageMetadata {
  readonly code?: string;
  readonly label?: string;
  readonly autoGenerated?: boolean;
}

export interface CaptionSourceMetadata {
  readonly platform?: string;
  readonly trackId?: string;
  readonly cueId?: string;
}

export interface CaptionCueLike {
  readonly id?: string;
  readonly text: string;
  readonly startTimeSeconds: number;
  readonly endTimeSeconds: number;
  readonly language?: CaptionLanguageMetadata;
  readonly source?: CaptionSourceMetadata;
}

export interface CaptionTrackLike {
  readonly id?: string;
  readonly label?: string;
  readonly language?: CaptionLanguageMetadata;
  readonly source?: CaptionSourceMetadata;
  readonly cues: readonly CaptionCueLike[];
}

export interface CaptionCue {
  readonly id: string;
  readonly trackId: string;
  readonly index: number;
  readonly originalText: string;
  readonly startTimeSeconds: number;
  readonly endTimeSeconds: number;
  readonly language: CaptionLanguageMetadata | null;
  readonly source: CaptionSourceMetadata | null;
}

export interface CaptionTrack {
  readonly id: string;
  readonly label: string | null;
  readonly language: CaptionLanguageMetadata | null;
  readonly source: CaptionSourceMetadata | null;
  readonly cues: readonly CaptionCue[];
}

export interface BilingualCaptionCue extends CaptionCue {
  readonly translatedText: string | null;
  readonly displayText: string;
}

export type CaptionDisplayLineKind = "original" | "translated";

export interface CaptionDisplayLine {
  readonly kind: CaptionDisplayLineKind;
  readonly text: string;
}

export interface RunCaptionTranslationPipelineOptions {
  readonly repository?: LocalTranslationRepository;
  readonly signal?: AbortSignal;
  readonly onProgress?: (result: TranslationJobResult) => void;
  readonly fetcher?: LocalTranslationFetch;
}

export interface CaptionTranslationPipelineResult {
  readonly track: CaptionTrack;
  readonly translationInputs: readonly TranslationInput[];
  readonly jobResult: TranslationJobResult;
  readonly displayCues: readonly BilingualCaptionCue[];
}

function normalizeIdentifier(value: string | undefined, fallback: string): string {
  const trimmed = value?.trim();
  return trimmed ? trimmed : fallback;
}

function emptyJobResult(): TranslationJobResult {
  return {
    status: "succeeded",
    translations: [],
    errors: [],
    progress: { total: 0, completed: 0, cacheHits: 0, cacheMisses: 0, failures: 0 },
  };
}

export function mapCaptionTrack(track: CaptionTrackLike): CaptionTrack {
  const trackId = normalizeIdentifier(track.id, "caption-track");
  const trackLanguage = track.language ?? null;
  const trackSource = track.source ?? null;

  return {
    id: trackId,
    label: track.label?.trim() || null,
    language: trackLanguage,
    source: trackSource,
    cues: track.cues.map((cue, index) => {
      const cueId = normalizeIdentifier(cue.id, `${trackId}:${index}`);
      return {
        id: cueId,
        trackId,
        index,
        originalText: cue.text,
        startTimeSeconds: cue.startTimeSeconds,
        endTimeSeconds: cue.endTimeSeconds,
        language: cue.language ?? trackLanguage,
        source: cue.source ?? trackSource,
      };
    }),
  };
}

export function buildCaptionTranslationInputs(
  cues: readonly CaptionCue[],
): readonly TranslationInput[] {
  return cues
    .filter((cue) => cue.originalText.trim().length > 0)
    .map((cue) => ({ id: cue.id, text: cue.originalText, format: "text" }));
}

export function composeBilingualCaptionCues(
  cues: readonly CaptionCue[],
  translations: readonly TranslationOutput[],
): readonly BilingualCaptionCue[] {
  const translationById = new Map(
    translations.map((translation) => [translation.id, translation.text]),
  );

  return cues.map((cue) => {
    const translatedText = translationById.get(cue.id) ?? null;
    const displayText = translatedText
      ? `${cue.originalText}\n${translatedText}`
      : cue.originalText;

    return {
      ...cue,
      translatedText,
      displayText,
    };
  });
}

export function captionDisplayLines(
  cue: BilingualCaptionCue,
  preferences: Pick<CaptionDisplayPreferences, "displayMode" | "captionLineOrder">,
): readonly CaptionDisplayLine[] {
  const originalLine: CaptionDisplayLine = { kind: "original", text: cue.originalText };
  const translatedLine: CaptionDisplayLine | null = cue.translatedText
    ? { kind: "translated", text: cue.translatedText }
    : null;

  if (preferences.displayMode === "side-by-side") return [originalLine];
  if (preferences.displayMode === "replace") return [translatedLine ?? originalLine];
  if (!translatedLine) return [originalLine];
  return preferences.captionLineOrder === "translated-first"
    ? [translatedLine, originalLine]
    : [originalLine, translatedLine];
}

export function getActiveCaptionCues<
  T extends Pick<CaptionCue, "startTimeSeconds" | "endTimeSeconds">,
>(cues: readonly T[], playbackTimeSeconds: number): readonly T[] {
  return cues.filter(
    (cue) =>
      cue.startTimeSeconds <= playbackTimeSeconds && playbackTimeSeconds < cue.endTimeSeconds,
  );
}

export async function runCaptionTranslationPipeline(
  settings: LocalTranslationSettings,
  captionTrack: CaptionTrackLike,
  options: RunCaptionTranslationPipelineOptions = {},
): Promise<CaptionTranslationPipelineResult> {
  const track = mapCaptionTrack(captionTrack);
  const translationInputs = buildCaptionTranslationInputs(track.cues);

  if (translationInputs.length === 0) {
    const jobResult = emptyJobResult();
    return {
      track,
      translationInputs,
      jobResult,
      displayCues: composeBilingualCaptionCues(track.cues, []),
    };
  }

  const runOptions: RunTranslationJobOptions = {
    repository: options.repository,
    signal: options.signal,
    onProgress: options.onProgress,
    fetcher: options.fetcher,
  };
  const jobResult = await LocalTranslationService.runJob(settings, translationInputs, runOptions);

  return {
    track,
    translationInputs,
    jobResult,
    displayCues: composeBilingualCaptionCues(track.cues, jobResult.translations),
  };
}
