import type { CaptionTrackLike } from "./caption-translation";

export interface GeneratedCaptionContext {
  readonly tabId: number;
  readonly tabUrl: string;
}

export type GeneratedCaptionFetch = (input: string, init: RequestInit) => Promise<Response>;

export interface FetchGeneratedCaptionTrackOptions extends GeneratedCaptionContext {
  readonly endpoint: string;
  readonly tabTitle: string;
  readonly signal: AbortSignal;
  readonly fetcher?: GeneratedCaptionFetch;
}

export class GeneratedCaptionError extends Error {
  readonly code:
    | "blank_endpoint"
    | "invalid_endpoint"
    | "offline_endpoint"
    | "invalid_response"
    | "cancelled";

  constructor(
    code: GeneratedCaptionError["code"],
    message: string,
    options?: { readonly cause?: unknown },
  ) {
    super(message, options);
    this.name = "GeneratedCaptionError";
    this.code = code;
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function isFiniteNumber(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value);
}

function readSegments(value: unknown): readonly unknown[] {
  if (!isRecord(value) || !Array.isArray(value.segments)) {
    throw new GeneratedCaptionError(
      "invalid_response",
      "STT response must include a segments array.",
    );
  }
  return value.segments;
}

function readLanguage(value: unknown): string | undefined {
  if (!isRecord(value) || typeof value.language !== "string") return undefined;
  return value.language.trim() || undefined;
}

function readSegmentText(segment: Record<string, unknown>, index: number): string {
  const text = segment.text;
  if (typeof text !== "string" || !text.trim()) {
    throw new GeneratedCaptionError(
      "invalid_response",
      `STT segment ${index} must include transcript text.`,
    );
  }
  return text.trim();
}

function readSegmentTime(
  segment: Record<string, unknown>,
  key: "start" | "end",
  index: number,
): number {
  const value = segment[key];
  if (!isFiniteNumber(value) || value < 0) {
    throw new GeneratedCaptionError(
      "invalid_response",
      `STT segment ${index} must include a non-negative ${key} time.`,
    );
  }
  return value;
}

export function normalizeSttSegmentsToCaptionTrack(
  response: unknown,
  context: GeneratedCaptionContext,
): CaptionTrackLike {
  const segments = readSegments(response);
  if (segments.length === 0) {
    throw new GeneratedCaptionError("invalid_response", "STT response did not include captions.");
  }

  const trackId = `generated-stt-tab-${context.tabId}`;
  const languageCode = readLanguage(response);
  const language = {
    code: languageCode,
    label: "Local STT",
    autoGenerated: true,
  };

  return {
    id: trackId,
    label: "Generated captions",
    language,
    source: { platform: "generated-stt", trackId },
    cues: segments.map((segment, zeroIndex) => {
      const index = zeroIndex + 1;
      if (!isRecord(segment)) {
        throw new GeneratedCaptionError(
          "invalid_response",
          `STT segment ${index} must be an object.`,
        );
      }
      const startTimeSeconds = readSegmentTime(segment, "start", index);
      const endTimeSeconds = readSegmentTime(segment, "end", index);
      if (endTimeSeconds <= startTimeSeconds) {
        throw new GeneratedCaptionError(
          "invalid_response",
          `STT segment ${index} must end after it starts.`,
        );
      }
      const id =
        typeof segment.id === "string" && segment.id.trim()
          ? segment.id.trim()
          : `${trackId}:${zeroIndex}`;
      return {
        id,
        text: readSegmentText(segment, index),
        startTimeSeconds,
        endTimeSeconds,
        language,
        source: { platform: "generated-stt", trackId, cueId: id },
      };
    }),
  };
}

function validateEndpoint(endpoint: string): string {
  const trimmed = endpoint.trim();
  if (!trimmed) {
    throw new GeneratedCaptionError("blank_endpoint", "Enter a local STT endpoint URL.");
  }

  try {
    const url = new URL(trimmed);
    if (url.protocol !== "http:" && url.protocol !== "https:") {
      throw new GeneratedCaptionError(
        "invalid_endpoint",
        "Use an http:// or https:// STT endpoint URL.",
      );
    }
  } catch (error) {
    if (error instanceof GeneratedCaptionError) throw error;
    throw new GeneratedCaptionError("invalid_endpoint", "Enter a valid STT endpoint URL.", {
      cause: error,
    });
  }

  return trimmed;
}

async function readEndpointFailure(response: Response): Promise<string> {
  const text = await response.text();
  if (!text.trim()) return response.statusText || "Local STT endpoint request failed.";
  try {
    const parsed: unknown = JSON.parse(text);
    if (isRecord(parsed)) {
      const error = parsed.error;
      if (typeof error === "string" && error.trim()) return error.trim();
      const message = parsed.message;
      if (typeof message === "string" && message.trim()) return message.trim();
    }
  } catch (error) {
    if (error instanceof SyntaxError) return text.trim();
    throw error;
  }
  return text.trim();
}

export async function fetchGeneratedCaptionTrack(
  options: FetchGeneratedCaptionTrackOptions,
): Promise<CaptionTrackLike> {
  const endpoint = validateEndpoint(options.endpoint);
  const fetcher: GeneratedCaptionFetch = options.fetcher ?? fetch;

  let response: Response;
  try {
    response = await fetcher(endpoint, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        tabId: options.tabId,
        tabTitle: options.tabTitle,
        tabUrl: options.tabUrl,
        source: "tab-audio-fixture",
      }),
      signal: options.signal,
    });
  } catch (error) {
    if (options.signal.aborted || error instanceof DOMException) {
      throw new GeneratedCaptionError("cancelled", "Generated caption run was cancelled.", {
        cause: error,
      });
    }
    throw new GeneratedCaptionError(
      "offline_endpoint",
      "Local STT endpoint is offline or unreachable.",
      { cause: error },
    );
  }

  if (!response.ok) {
    throw new GeneratedCaptionError("offline_endpoint", await readEndpointFailure(response));
  }

  const parsed: unknown = await response.json();
  return normalizeSttSegmentsToCaptionTrack(parsed, options);
}
