import { describe, expect, test } from "vitest";
import type { CaptionTrackLike } from "./caption-translation";
import {
  preferredYouTubeCaptionLanguageCodes,
  selectInitialCaptionWindow,
  selectYouTubeCaptionTrack,
  type YouTubeCaptionTrackMetadata,
} from "./youtube-captions";

function trackWithCues(count: number): CaptionTrackLike {
  return {
    id: "youtube",
    label: "English",
    source: { platform: "youtube", trackId: "en" },
    cues: Array.from({ length: count }, (_, index) => ({
      id: `cue-${index}`,
      text: `Cue ${index}`,
      startTimeSeconds: index * 10,
      endTimeSeconds: index * 10 + 5,
    })),
  };
}

describe("selectInitialCaptionWindow", () => {
  test("selects cues around the current video time", () => {
    const selected = selectInitialCaptionWindow(trackWithCues(12), {
      currentTimeSeconds: 42,
      maxCueCount: 4,
    });

    expect(selected.cues.map((cue) => cue.id)).toEqual(["cue-2", "cue-3", "cue-4", "cue-5"]);
  });

  test("falls back to the first cues when current time is unavailable", () => {
    const selected = selectInitialCaptionWindow(trackWithCues(12), { maxCueCount: 4 });

    expect(selected.cues.map((cue) => cue.id)).toEqual(["cue-0", "cue-1", "cue-2", "cue-3"]);
  });
});

describe("selectYouTubeCaptionTrack", () => {
  function track(
    languageCode: string,
    autoGenerated: boolean,
    label = languageCode,
  ): YouTubeCaptionTrackMetadata {
    return {
      baseUrl: `https://youtube.example/captions?lang=${languageCode}`,
      label,
      languageCode,
      vssId: `${autoGenerated ? "a." : "."}${languageCode}`,
      autoGenerated,
    };
  }

  test("prefers English and Korean caption tracks before unrelated languages", () => {
    expect(
      selectYouTubeCaptionTrack([track("ja", false), track("ko", true), track("fr", false)])
        ?.languageCode,
    ).toBe("ko");
    expect(
      selectYouTubeCaptionTrack([track("ja", false), track("en", false), track("ko", false)])
        ?.languageCode,
    ).toBe("en");
  });

  test("keeps explicit YouTube caption selection ahead of language defaults", () => {
    const japaneseTrack = track("ja", false, "Japanese");
    expect(
      selectYouTubeCaptionTrack([track("en", false), japaneseTrack], {
        selectedLabel: "Japanese",
      }),
    ).toBe(japaneseTrack);
  });

  test("keeps selected YouTube caption language ahead of default language order", () => {
    const englishTrack = track("en", false, "English");
    const koreanTrack = track("ko", false, "Korean");

    expect(
      selectYouTubeCaptionTrack([englishTrack, koreanTrack], {
        selectedLanguageCode: "ko",
      }),
    ).toBe(koreanTrack);
    expect(
      selectYouTubeCaptionTrack([koreanTrack, englishTrack], {
        selectedLanguageCode: "en",
      }),
    ).toBe(englishTrack);
  });

  test("uses Korean title hints only when no explicit YouTube caption language is selected", () => {
    expect(preferredYouTubeCaptionLanguageCodes({ videoTitle: "한국어 영상 제목" })).toEqual([
      "ko",
      "en",
    ]);
    expect(
      preferredYouTubeCaptionLanguageCodes({
        selectedLanguageCode: "en",
        videoTitle: "한국어 영상 제목",
      }),
    ).toEqual(["en", "ko"]);
  });
});
