import type { CaptionCueLike, CaptionTrackLike } from "./caption-translation";

export interface YouTubeCaptionTrackMetadata {
  readonly baseUrl: string;
  readonly label: string;
  readonly languageCode?: string;
  readonly vssId?: string;
  readonly autoGenerated: boolean;
}

export interface SelectYouTubeCaptionTrackOptions {
  readonly selectedBaseUrl?: string;
  readonly selectedLabel?: string;
}

export interface SelectInitialCaptionWindowOptions {
  readonly maxCueCount?: number;
  readonly currentTimeSeconds?: number | null;
}

interface Json3Segment {
  readonly utf8?: unknown;
}

interface Json3Event {
  readonly tStartMs?: unknown;
  readonly dDurationMs?: unknown;
  readonly segs?: unknown;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function textFromName(value: unknown): string | null {
  if (!isRecord(value)) return null;
  if (typeof value.simpleText === "string") return value.simpleText.trim() || null;
  if (!Array.isArray(value.runs)) return null;
  const text = value.runs
    .map((run) => (isRecord(run) && typeof run.text === "string" ? run.text : ""))
    .join("")
    .trim();
  return text || null;
}

function normalizeTrackBase(value: string): string {
  try {
    const url = new URL(value);
    url.searchParams.set("fmt", "json3");
    return url.toString();
  } catch {
    const separator = value.includes("?") ? "&" : "?";
    const withoutExistingFormat = value.replace(/([?&])fmt=[^&]*&?/, "$1").replace(/[?&]$/, "");
    return `${withoutExistingFormat}${separator}fmt=json3`;
  }
}

function trackIdFor(metadata: YouTubeCaptionTrackMetadata): string {
  return metadata.vssId?.trim() || metadata.languageCode?.trim() || metadata.baseUrl;
}

function languageFor(metadata: YouTubeCaptionTrackMetadata) {
  return {
    code: metadata.languageCode,
    label: metadata.label,
    autoGenerated: metadata.autoGenerated,
  };
}

export function parseYouTubeCaptionTracks(
  playerResponse: unknown,
): readonly YouTubeCaptionTrackMetadata[] {
  if (!isRecord(playerResponse)) return [];
  const captions = playerResponse.captions;
  if (!isRecord(captions)) return [];
  const renderer = captions.playerCaptionsTracklistRenderer;
  if (!isRecord(renderer) || !Array.isArray(renderer.captionTracks)) return [];

  return renderer.captionTracks
    .map((track): YouTubeCaptionTrackMetadata | null => {
      if (!isRecord(track) || typeof track.baseUrl !== "string" || !track.baseUrl.trim()) {
        return null;
      }
      const label = textFromName(track.name) ?? "YouTube captions";
      const kind = typeof track.kind === "string" ? track.kind : "";
      const vssId = typeof track.vssId === "string" ? track.vssId : undefined;
      return {
        baseUrl: track.baseUrl,
        label,
        languageCode: typeof track.languageCode === "string" ? track.languageCode : undefined,
        vssId,
        autoGenerated: kind === "asr" || vssId?.startsWith("a.") === true,
      };
    })
    .filter((track): track is YouTubeCaptionTrackMetadata => track !== null);
}

export function normalizeYouTubeCaptionUrl(baseUrl: string): string {
  return normalizeTrackBase(baseUrl);
}

export function selectYouTubeCaptionTrack(
  tracks: readonly YouTubeCaptionTrackMetadata[],
  options: SelectYouTubeCaptionTrackOptions = {},
): YouTubeCaptionTrackMetadata | null {
  if (tracks.length === 0) return null;
  const selectedBaseUrl = options.selectedBaseUrl
    ? normalizeYouTubeCaptionUrl(options.selectedBaseUrl)
    : null;
  if (selectedBaseUrl) {
    const matchingBaseUrl = tracks.find(
      (track) => normalizeYouTubeCaptionUrl(track.baseUrl) === selectedBaseUrl,
    );
    if (matchingBaseUrl) return matchingBaseUrl;
  }

  const selectedLabel = options.selectedLabel?.trim().toLocaleLowerCase();
  if (selectedLabel) {
    const matchingLabel = tracks.find(
      (track) => track.label.trim().toLocaleLowerCase() === selectedLabel,
    );
    if (matchingLabel) return matchingLabel;
  }

  return tracks.find((track) => !track.autoGenerated) ?? tracks[0] ?? null;
}

export function parseYouTubeCaptionPayload(
  payload: string,
  metadata: YouTubeCaptionTrackMetadata,
): CaptionTrackLike {
  if (payload.trimStart().startsWith("<")) {
    throw new Error("Only YouTube JSON3 caption payloads are supported.");
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(payload);
  } catch {
    throw new Error("YouTube JSON3 caption payload is malformed.");
  }

  if (!isRecord(parsed) || !Array.isArray(parsed.events)) {
    throw new Error("YouTube JSON3 caption payload is malformed.");
  }

  const trackId = trackIdFor(metadata);
  const language = languageFor(metadata);
  const cues = parsed.events
    .map((event): Omit<CaptionCueLike, "id" | "source"> | null => {
      if (!isRecord(event)) return null;
      const jsonEvent = event as Json3Event;
      if (typeof jsonEvent.tStartMs !== "number") return null;
      if (typeof jsonEvent.dDurationMs !== "number" || jsonEvent.dDurationMs <= 0) return null;
      if (!Array.isArray(jsonEvent.segs)) return null;
      const text = jsonEvent.segs
        .map((segment: Json3Segment) =>
          isRecord(segment) && typeof segment.utf8 === "string" ? segment.utf8 : "",
        )
        .join("")
        .trim();
      if (!text) return null;
      return {
        text,
        startTimeSeconds: jsonEvent.tStartMs / 1000,
        endTimeSeconds: (jsonEvent.tStartMs + jsonEvent.dDurationMs) / 1000,
        language,
      };
    })
    .filter((cue): cue is Omit<CaptionCueLike, "id" | "source"> => cue !== null)
    .sort((left, right) => left.startTimeSeconds - right.startTimeSeconds)
    .map((cue, index) => ({
      ...cue,
      id: `${trackId}:${index}`,
      source: { platform: "youtube", trackId, cueId: `${trackId}:${index}` },
    }));

  return {
    id: trackId,
    label: metadata.label,
    language,
    source: { platform: "youtube", trackId },
    cues,
  };
}

export function selectInitialCaptionWindow(
  track: CaptionTrackLike,
  options: SelectInitialCaptionWindowOptions = {},
): CaptionTrackLike {
  const maxCueCount = Math.max(1, options.maxCueCount ?? 12);
  const currentTimeSeconds = options.currentTimeSeconds;
  if (
    typeof currentTimeSeconds === "number" &&
    Number.isFinite(currentTimeSeconds) &&
    track.cues.length > maxCueCount
  ) {
    const currentCueIndex = track.cues.findIndex(
      (cue) =>
        cue.startTimeSeconds <= currentTimeSeconds && currentTimeSeconds < cue.endTimeSeconds,
    );
    const nextCueIndex = track.cues.findIndex((cue) => currentTimeSeconds < cue.startTimeSeconds);
    const anchorIndex =
      currentCueIndex >= 0
        ? currentCueIndex
        : nextCueIndex >= 0
          ? nextCueIndex
          : track.cues.length - 1;
    const startIndex = Math.max(
      0,
      Math.min(track.cues.length - maxCueCount, anchorIndex - Math.floor(maxCueCount / 2)),
    );
    return {
      ...track,
      cues: track.cues.slice(startIndex, startIndex + maxCueCount),
    };
  }
  return {
    ...track,
    cues: track.cues.slice(0, maxCueCount),
  };
}
