export const tw = {
  activeTerminalTab: "activeTerminalTab [background:var(--card)] [color:var(--foreground)]",
  activeToolTab:
    "activeToolTab [box-shadow:inset_0_-2px_var(--primary)] [color:var(--foreground)] [font-weight:600] [background:var(--accent)]! [color:var(--foreground)]!",
  activitySlot: "activitySlot [min-width:0]",
  appShell:
    "appShell [background:var(--background)] [display:grid] [grid-template-rows:30px_29px_minmax(0,_1fr)_20px] [height:100%] [min-width:800px] [overflow:hidden] [position:relative] [&_button]:rounded-sm [&_input]:rounded-sm [&_textarea]:rounded-sm [&_select]:rounded-sm [&_button:not(:disabled):hover]:[background-color:color-mix(in_oklch,_var(--foreground)_7%,_transparent)]",
  binaryConflict:
    "binaryConflict [align-items:center] [display:flex] [flex-direction:column] [justify-content:center] [padding:40px] [text-align:center] [&_p]:[color:var(--muted-foreground)] [&_p]:[max-width:480px] [&>_div]:[display:flex] [&>_div]:[gap:8px]",
  binaryMetadata:
    "binaryMetadata [display:grid] [gap:4px] [color:var(--muted-foreground)] [font-family:var(--font-family-code)] [font-size:11px]",
  blameView:
    "blameView [&>_div:hover]:[background:var(--muted)] [&>_div]:[display:grid] [&>_div]:[font-size:10px] [&>_div]:[grid-template-columns:50px_70px_120px_minmax(200px,_1fr)] [&>_div]:[min-height:22px] [&>_div_>_*]:[align-items:center] [&>_div_>_*]:[border-right:1px_solid_var(--border)] [&>_div_>_*]:[display:flex] [&>_div_>_*]:[margin:0] [&>_div_>_*]:[padding:2px_7px] [&_pre]:[font-family:var(--font-family-code)] [&_pre]:[overflow-x:auto] [&_pre]:[white-space:pre]",
  bottomCollapsed:
    "bottomCollapsed [border-top:0] [height:0] [grid-template-rows:0] [overflow:hidden]",
  bottomPanel:
    "bottomPanel [background:var(--card)] rounded-t-xl rounded-b-none [display:grid] [grid-template-rows:4px_31px_minmax(0,_1fr)] [min-height:0] [overflow:hidden]",
  bottomTerminalPanel: "bottomTerminalPanel [grid-template-rows:4px_minmax(0,_1fr)]",
  bottomResizer:
    'bottomResizer [background:transparent] [cursor:ns-resize] [position:relative] [z-index:3] [&::after]:[background:var(--input)] [&::after]:[content:\\"\\"] [&::after]:[height:1px] [&::after]:[left:0] [&::after]:[position:absolute] [&::after]:[right:0] [&::after]:[top:1px] [&:hover::after]:[background:var(--primary)] [&:hover::after]:[height:2px] [&:focus-visible::after]:[background:var(--primary)] [&:focus-visible::after]:[height:2px]',
  branchComparison:
    "branchComparison [display:flex] [flex-direction:column] [gap:6px] [padding:12px] [&>_span]:[color:var(--muted-foreground)] [&_pre]:[background:var(--muted)] [&_pre]:[border:1px_solid_var(--border)] [&_pre]:rounded-lg [&_pre]:[max-height:220px] [&_pre]:[overflow:auto] [&_pre]:[padding:8px]",
  branchPane:
    "branchPane [background:var(--card)] [min-height:0] [min-width:0] [border-right:1px_solid_var(--border)] [display:grid] [grid-template-rows:31px_38px_29px_minmax(0,_1fr)] max-[1050px]:[display:none]",
  branchRail:
    "branchRail [background:var(--card)] [border-right:1px_solid_var(--border)] [min-height:0] [overflow:hidden] [&_button]:[align-items:center] [&_button]:[background:transparent] [&_button]:[color:var(--muted-foreground)] [&_button]:[display:flex] [&_button]:[flex-direction:column] [&_button]:[gap:5px] [&_button]:[height:100%] [&_button]:[justify-content:flex-start] [&_button]:[padding:7px_0] [&_button]:[width:100%] [&_button_span]:[font-size:10px] [&_button_span]:[writing-mode:vertical-rl] [&_button_span]:[transform:rotate(180deg)]",
  changeNavigator:
    "changeNavigator [border-right:1px_solid_var(--border)] [display:grid] [grid-template-rows:38px_minmax(0,_1fr)_auto] [min-height:0] [min-width:0] [outline:0] [position:relative]",
  changeNavigatorActions:
    "changeNavigatorActions [border-top:1px_solid_var(--border)] [display:flex] [flex-wrap:wrap] [gap:4px] [padding:5px] [&_button]:[background:transparent] [&_button]:[color:var(--muted-foreground)] [&_button]:[min-height:25px] [&_button]:[padding:0_6px]",
  changeNavigatorGroup:
    "changeNavigatorGroup [&>_header]:[align-items:center] [&>_header]:[background:var(--secondary)] [&>_header]:[border-bottom:1px_solid_var(--border)] [&>_header]:[border-top:1px_solid_var(--border)] [&>_header]:[display:flex] [&>_header]:[gap:6px] [&>_header]:[height:29px] [&>_header]:[padding:0_7px] [&>_header]:[position:sticky] [&>_header]:[top:0] [&>_header]:[z-index:2] [&:first-child_>_header]:[border-top:0] [&>_header_small]:[color:var(--disabled-foreground)] [&>_header_span]:[flex:1] [&>_header_button]:[background:transparent] [&>_header_button]:[color:var(--primary)] [&>_header_button]:[padding:0_5px]",
  changeNavigatorList: "changeNavigatorList [min-height:0] [overflow:auto]",
  changeNavigatorRow:
    "changeNavigatorRow [align-items:center] [background:transparent] rounded-none! [display:flex] [gap:5px] [min-height:29px] [padding:3px_7px] [text-align:left] [width:100%] [&.selected]:[background:var(--accent)] [&[aria-current=true]]:[background:var(--accent)] [&.multiSelected]:[background:color-mix(in_oklch,_var(--accent)_62%,_transparent)] [&_small]:[color:var(--disabled-foreground)]",
  changeNavigatorToolbar:
    "changeNavigatorToolbar [align-items:center] [border-bottom:1px_solid_var(--border)] [display:flex] [gap:4px] [padding:5px_6px] [&>_label]:[align-items:center] [&>_label]:[background:var(--secondary)] [&>_label]:[border:1px_solid_var(--border)] [&>_label]:rounded-lg [&>_label]:[display:flex] [&>_label]:[flex:1] [&>_label]:[gap:5px] [&>_label]:[height:27px] [&>_label]:[padding:0_7px] [&>_label:focus-within]:[border-color:var(--primary)] [&>_label:focus-within]:[box-shadow:0_0_0_2px_color-mix(in_oklch,_var(--primary)_22%,_transparent)] [&_input]:[background:transparent] [&_input]:[border:0] [&_input]:[min-width:0] [&_input]:[outline:0] [&_input]:[width:100%]",
  changelistBar:
    "changelistBar [display:flex] [gap:5px] [min-width:0] [padding-bottom:5px] [&_select]:[background:var(--secondary)] [&_select]:[border:1px_solid_var(--border)] [&_select]:rounded-sm [&_select]:[flex:1] [&_select]:[min-width:0] [&_select]:[padding:0_6px] [&_button]:[height:24px]",
  changesWorkspace:
    "changesWorkspace [background:var(--card)] [display:grid] [grid-template-columns:minmax(190px,_var(--changes-navigator-width,_250px))_minmax(420px,_1fr)_minmax(280px,_var(--commit-rail-width,_315px))] [min-height:0] [min-width:0] max-[1120px]:[grid-template-columns:minmax(210px,_245px)_minmax(0,_1fr)] max-[1120px]:[position:relative] max-[1120px]:[&>_.commitRail]:[bottom:0] max-[1120px]:[&>_.commitRail]:[box-shadow:var(--shadow-lg)] max-[1120px]:[&>_.commitRail]:[position:absolute] max-[1120px]:[&>_.commitRail]:[right:0] max-[1120px]:[&>_.commitRail]:[top:0] max-[1120px]:[&>_.commitRail]:[transform:translateX(102%)] max-[1120px]:[&>_.commitRail]:[transition:transform_120ms_ease-out] max-[1120px]:[&>_.commitRail]:[width:min(var(--commit-rail-width,_340px),_calc(100%_-_220px))] max-[1120px]:[&>_.commitRail]:[z-index:15] max-[1120px]:[&.commitRailOpen_>_.commitRail]:[transform:translateX(0)]",
  changesWorkspaceFocused:
    "changesWorkspaceFocused [grid-template-columns:0_minmax(0,_1fr)_0] [&>_.changeNavigator]:[overflow:hidden] [&>_.changeNavigator]:[visibility:hidden] [&>_.commitRail]:[overflow:hidden] [&>_.commitRail]:[visibility:hidden]",
  changesToolWindow:
    "changesToolWindow rounded-xl [grid-template-columns:minmax(0,_1fr)]! [grid-template-rows:29px_minmax(150px,_3fr)_minmax(120px,_2fr)] [overflow:hidden] max-[1120px]:[grid-template-columns:minmax(0,_1fr)]! max-[1120px]:[position:relative] [&>_.changeNavigator]:[border-bottom:1px_solid_var(--border)] [&>_.changeNavigator]:[border-right:0] [&>_.diffViewer]:[display:none] [&>_.focusedDiffViewer]:[display:grid] [&>_.commitRail]:[border-left:0] [&>_.commitRail]:[border-top:1px_solid_var(--border)] [&>_.commitRail]:[padding:6px] max-[1120px]:[&>_.commitRail]:[box-shadow:none] max-[1120px]:[&>_.commitRail]:[position:relative] max-[1120px]:[&>_.commitRail]:[transform:none] max-[1120px]:[&>_.commitRail]:[width:auto]",
  collectionIntro:
    "collectionIntro [align-items:center] [border-bottom:1px_solid_var(--border)] [display:flex] [gap:10px] [min-height:48px] [padding:8px_14px] [background:var(--muted)] [&_div]:[flex:1] [&_p]:[color:var(--muted-foreground)] [&_p]:[margin:2px_0_0]",
  collectionRow:
    "collectionRow [align-items:center] [border-bottom:1px_solid_var(--border)] [display:flex] [gap:10px] [min-height:48px] [padding:8px_14px] [&_div]:[flex:1] [&_small]:[color:var(--disabled-foreground)] [&_small]:[display:block] [&_small]:[margin-top:3px] [border-bottom:0]",
  collectionTool:
    "collectionTool [&_button]:[background:var(--muted)] [&_button]:[border:1px_solid_var(--border)] [&_button]:rounded-sm [&_button]:[height:27px] [&_button]:[padding:0_9px] [&_button]:[white-space:nowrap] [height:100%] [overflow:auto]",
  projectSearchDialog:
    "projectSearchDialog [display:grid] [grid-template-rows:auto_auto_27px_minmax(210px,_1fr)] [height:min(610px,_calc(100vh_-_82px))] [min-height:0] [overflow:hidden]",
  projectSearchQuery:
    "projectSearchQuery [align-items:end] [border-bottom:1px_solid_var(--border)] [display:grid] [gap:5px] [grid-template-columns:minmax(0,_1fr)_auto_auto_auto_auto] [padding:8px_9px] [&>_button]:[min-width:28px]",
  projectSearchStatus:
    "projectSearchStatus [align-items:center] [background:var(--muted)] [border-bottom:1px_solid_var(--border)] [color:var(--muted-foreground)] [display:flex] [font-size:10px] [padding:0_6px_0_10px] [&>_span]:[flex:1] [&>_button]:[height:23px] [&>_button]:[font-size:10px]",
  projectSearchResults:
    "projectSearchResults [min-height:0] [overflow:auto] [padding:4px] [&>_[role=status]]:[margin:36px_auto] [&>_p]:[color:var(--muted-foreground)] [&>_p]:[padding:36px_12px] [&>_p]:[text-align:center] [&_li]:[min-height:39px] [&_li_[data-slot=item-description]]:[font-family:var(--font-family-code)] [&_li_[data-slot=item-description]]:[font-size:10px] [&_li_code]:[color:var(--disabled-foreground)] [&_li_code]:[font-size:9px] [&_li_code]:[max-width:310px] [&_li_code]:[overflow:hidden] [&_li_code]:[text-overflow:ellipsis] [&_li_code]:[white-space:nowrap]",
  replaceInFilesDialog:
    "replaceInFilesDialog [display:grid] [grid-template-rows:auto_auto_auto_minmax(0,_1fr)_auto] [height:min(680px,_calc(100vh_-_70px))] [min-height:0] [&>_footer]:[border-top:1px_solid_var(--border)] [&>_footer]:[display:flex] [&>_footer]:[gap:8px] [&>_footer]:[justify-content:flex-end] [&>_footer]:[padding:9px_12px]",
  replaceInFilesQuery:
    "replaceInFilesQuery [border-bottom:1px_solid_var(--border)] [display:grid] [gap:8px] [grid-template-columns:minmax(0,_1fr)_minmax(0,_1fr)_auto] [padding:10px_12px] [&>_div:last-child]:[align-items:flex-end] [&>_div:last-child]:[display:flex] [&>_div:last-child]:[gap:4px]",
  replaceInFilesStatus:
    "replaceInFilesStatus [align-items:center] [background:var(--muted)] [border-bottom:1px_solid_var(--border)] [color:var(--muted-foreground)] [display:flex] [min-height:30px] [padding:4px_12px] [&>_span]:[flex:1] [&>_button]:[background:transparent] [&>_button]:[color:var(--primary)]",
  replaceInFilesResults:
    "replaceInFilesResults [min-height:0] [overflow:auto] [padding:5px_7px] [&>_p]:[color:var(--muted-foreground)] [&>_p]:[margin:24px] [&>_p[role=alert]]:[color:var(--destructive)] [&_li]:rounded-sm [&_li_code]:[color:var(--disabled-foreground)] [&_li_code]:[font-size:9px]",
  commandbar:
    "commandbar [align-items:center] [background:var(--card)] [border-bottom:1px_solid_var(--border)] rounded-t-lg rounded-b-none [display:flex] [gap:3px] [height:29px] [left:var(--editor-left,_30px)] [padding:0_5px_0_0] [position:absolute] [right:30px] [top:30px] [z-index:8] [&>_button]:[align-items:center] [&>_button]:[background:transparent] [&>_button]:[display:flex] [&>_button]:[gap:6px] [&>_button]:[height:25px] [&>_button]:[padding:0_7px] [&>_button:hover]:[background:var(--muted)] [&>_button_>_em]:[align-items:center] [&>_button_>_em]:[background:var(--primary)] [&>_button_>_em]:rounded-lg [&>_button_>_em]:[color:var(--primary-foreground)] [&>_button_>_em]:[display:inline-flex] [&>_button_>_em]:[font-size:9px] [&>_button_>_em]:[font-style:normal] [&>_button_>_em]:[height:15px] [&>_button_>_em]:[justify-content:center] [&>_button_>_em]:[min-width:15px] [&>_button_>_em]:[padding:0_4px]",
  commitRail:
    "commitRail [border-left:1px_solid_var(--border)] [display:grid] [gap:7px] [grid-template-rows:34px_auto_auto_minmax(110px,_1fr)_auto] [min-height:0] [min-width:0] [padding:7px] [position:relative] [&>_.verticalResizeHandle]:[left:-4px] [&>_.verticalResizeHandle]:[right:auto] [&>_header]:[align-items:center] [&>_header]:[display:flex] [&>_header]:[gap:6px] [&>_header_small]:[color:var(--disabled-foreground)] [&>_header_small]:[margin-left:auto] [&_textarea]:[background:var(--secondary)] [&_textarea]:[border:1px_solid_var(--border)] [&_textarea]:[min-height:110px] [&_textarea]:[padding:9px] [&_textarea]:[resize:none] [&>_footer]:[align-items:center] [&>_footer]:[border-top:1px_solid_var(--border)] [&>_footer]:[display:grid] [&>_footer]:[gap:5px] [&>_footer]:[grid-template-columns:minmax(0,_1fr)_auto_auto] [&>_footer]:[padding-top:7px] [&>_footer_>_button]:[background:var(--secondary)] [&>_footer_>_button]:[border:1px_solid_var(--border)] [&>_footer_>_button]:[min-height:29px] [&>_footer_>_button]:[padding:0_9px] max-[1120px]:[bottom:0] max-[1120px]:[box-shadow:var(--shadow-lg)] max-[1120px]:[position:absolute] max-[1120px]:[right:0] max-[1120px]:[top:0] max-[1120px]:[transform:translateX(102%)] max-[1120px]:[transition:transform_120ms_ease-out] max-[1120px]:[width:min(var(--commit-rail-width,_340px),_calc(100%_-_220px))] max-[1120px]:[z-index:15] max-[1120px]:[&>_.verticalResizeHandle]:[display:none]",
  commitRailOpen: "commitRailOpen",
  commitToolWindowHeader:
    "commitToolWindowHeader [align-items:center] [background:var(--secondary)] [border-bottom:1px_solid_var(--border)] [display:flex] [gap:2px] [height:29px] [padding:0_5px_0_8px] [&>_strong]:[font-size:11px] [&>_span]:[flex:1]",
  commitRow:
    "commitRow [align-items:stretch]! [background:transparent] rounded-none! [display:grid]! [font-weight:400]! [grid-template-columns:34px_minmax(190px,_1fr)_100px_145px] [grid-template-rows:minmax(0,_1fr)] [height:20px]! [justify-content:start]! [left:0] [padding:0_3px]! [position:absolute] [right:0] [text-align:left] [top:0] [width:100%] [&:hover]:[background:color-mix(in_oklch,_var(--accent)_42%,_transparent)] [&>_*]:[align-items:center] [&>_*]:[display:flex] [&>_*]:[min-height:0] [&>_*]:[min-width:0] [&>_*]:[padding:0_4px] [&_strong]:[font-weight:600] [&>_span:last-child]:[color:var(--muted-foreground)] [&>_span:last-child]:[font-size:11px]",
  commitScroller:
    "commitScroller [background:var(--card)] [min-height:0] [overflow:auto] [position:relative]",
  commitSubject:
    "commitSubject [gap:6px] [&_em]:[background:color-mix(in_oklch,_var(--primary)_16%,_var(--card))] [&_em]:[border:1px_solid_color-mix(in_oklch,_var(--primary)_35%,_var(--border))] [&_em]:rounded-xs [&_em]:[color:var(--primary)] [&_em]:[flex:none] [&_em]:[font-size:9px] [&_em]:[font-style:normal] [&_em]:[padding:1px_4px] [&_code]:[color:var(--disabled-foreground)] [&_code]:[font-size:9px] [&_code]:[margin-left:auto]",
  configComposer:
    "configComposer [display:grid] [gap:8px] [grid-template-columns:minmax(180px,_1fr)_minmax(220px,_2fr)_auto] [padding:9px_11px]",
  configTable:
    "configTable [min-width:660px] [&>_div]:[align-items:center] [&>_div]:[border-top:1px_solid_var(--border)] [&>_div]:[display:grid] [&>_div]:[gap:10px] [&>_div]:[grid-template-columns:minmax(170px,_1.2fr)_minmax(190px,_1.5fr)_75px_minmax(130px,_1fr)_58px] [&>_div]:[min-height:36px] [&>_div]:[padding:5px_11px] [&>_div:first-child]:[background:var(--muted)] [&>_div:first-child]:[border-top:0] [&>_div:first-child]:[color:var(--muted-foreground)] [&>_div:first-child]:[font-size:11px] [&>_div:first-child]:[position:sticky] [&>_div:first-child]:[top:0] [&_code]:[min-width:0] [&_code]:[overflow:hidden] [&_code]:[text-overflow:ellipsis] [&_code]:[white-space:nowrap] [&_span]:[min-width:0] [&_span]:[overflow:hidden] [&_span]:[text-overflow:ellipsis] [&_span]:[white-space:nowrap] [&_small]:[min-width:0] [&_small]:[overflow:hidden] [&_small]:[text-overflow:ellipsis] [&_small]:[white-space:nowrap]",
  conflictGrid:
    "conflictGrid [display:grid] [grid-template-columns:repeat(2,_minmax(0,_1fr))] [grid-template-rows:repeat(2,_minmax(0,_1fr))] [min-height:0]",
  conflictPane:
    "conflictPane [&_select]:[background:var(--muted)] [&_select]:[border:1px_solid_var(--border)] [&_select]:rounded-sm [&_select]:[min-height:26px] [&_select]:[padding:0_8px] [display:grid] [grid-template-rows:32px_minmax(0,_1fr)] [min-height:0] [min-width:0] [&:nth-child(odd)]:[border-right:1px_solid_var(--border)] [&:nth-child(-n_+_2)]:[border-bottom:1px_solid_var(--border)] [&>_header]:[align-items:center] [&>_header]:[background:var(--muted)] [&>_header]:[border-bottom:1px_solid_var(--border)] [&>_header]:[display:flex] [&>_header]:[gap:4px] [&>_header]:[padding:2px_7px] [&>_header_strong]:[flex:1] [&>_div]:[min-height:0] [&>_div]:[overflow:hidden]",
  detailsPane:
    "detailsPane [background:var(--card)] [min-height:0] [min-width:0] [border-left:1px_solid_var(--border)] [display:grid] [grid-template-rows:26px_minmax(0,_1fr)] [position:relative] [&>_.verticalResizeHandle]:[left:-4px] [&>_.verticalResizeHandle]:[right:auto]",
  detailsToolbar:
    "detailsToolbar [align-items:center] [border-bottom:1px_solid_var(--border)] [display:flex] [gap:1px] [padding:2px_5px] [&>_select]:[background:var(--secondary)] [&>_select]:[border:1px_solid_var(--border)] [&>_select]:[height:25px] [&>_select]:[max-width:170px] [&>_select]:[padding:0_6px]",
  detailsViewOptions: "detailsViewOptions [display:grid] [gap:3px] [padding:5px]",
  diffSearch:
    "diffSearch [align-items:center] [background:var(--secondary)] [border:1px_solid_var(--border)] rounded-lg [display:flex] [height:26px] [padding:0_6px] [width:128px] [&:focus-within]:[border-color:var(--primary)] [&:focus-within]:[box-shadow:0_0_0_2px_color-mix(in_oklch,_var(--primary)_22%,_transparent)] [&_input]:[background:transparent] [&_input]:[border:0] [&_input]:[min-width:0] [&_input]:[outline:0] [&_input]:[width:100%] [&_small]:[color:var(--disabled-foreground)]",
  diffStat:
    "diffStat [display:flex] [font-size:9px] [gap:4px] [margin-left:auto] [&_i]:[color:var(--success)] [&_i]:[font-style:normal] [&_b]:[color:var(--destructive)] [&_b]:[font-weight:400]",
  diffViewer:
    "diffViewer [background:var(--card)] [display:grid] [grid-template-rows:36px_auto_minmax(0,_1fr)] [min-height:0] [min-width:0] [outline:0] [position:relative] [&:focus-visible]:[box-shadow:inset_0_0_0_2px_color-mix(in_oklch,_var(--primary)_55%,_transparent)]",
  diffViewerContent:
    "diffViewerContent [min-height:0] [overflow:auto] [&>_pre]:[font-family:var(--font-family-code)] [&>_pre]:[font-size:11px] [&>_pre]:[line-height:1.55] [&>_pre]:[margin:0] [&>_pre]:[min-height:100%] [&>_pre]:[padding:12px] [&>_pre]:[white-space:pre] [&>_pre.wrappedDiff]:[white-space:pre-wrap] [&>_pre.wrappedDiff]:[word-break:break-word] [&>_pre_>_span]:[display:inline]",
  diffViewerHeader:
    "diffViewerHeader [align-items:center] [border-bottom:1px_solid_var(--border)] [display:flex] [gap:6px] [min-width:0] [padding:4px_7px] [&>_span:last-of-type]:[flex:1] [&_strong]:[min-width:40px] [&_small]:[color:var(--disabled-foreground)] [&_small]:[flex:none]",
  diffViewerToolbar:
    "diffViewerToolbar [align-items:center] [border-bottom:1px_solid_var(--border)] [display:flex] [gap:6px] [min-width:0] [padding:4px_7px] [&>_span]:[flex:1] [background:var(--secondary)] [flex-wrap:wrap] [min-height:34px] [&_label]:[align-items:center] [&_label]:[color:var(--muted-foreground)] [&_label]:[display:inline-flex] [&_label]:[font-size:10px] [&_label]:[gap:5px] [&_label]:[white-space:nowrap] [&_button]:[background:var(--card)] [&_button]:[border:1px_solid_var(--border)] [&_button]:[min-height:25px] [&_button]:[padding:0_7px] [&_select]:[background:var(--card)] [&_select]:[border:1px_solid_var(--border)] [&_select]:[min-height:25px] [&_select]:[padding:0_7px]",
  ellipsis:
    "ellipsis [min-width:0] [overflow:hidden] [text-overflow:ellipsis] [white-space:nowrap]",
  exportToHtmlDialog:
    "exportToHtmlDialog [display:grid] [grid-template-rows:auto_minmax(0,_1fr)_auto] [max-height:min(650px,_calc(100vh_-_70px))] [min-height:430px] [&>_main]:[display:flex] [&>_main]:[flex-direction:column] [&>_main]:[gap:14px] [&>_main]:[min-height:0] [&>_main]:[overflow:auto] [&>_main]:[padding:16px_20px] [&>_main_>_label]:[display:flex] [&>_main_>_label]:[flex-direction:column] [&>_main_>_label]:[font-weight:600] [&>_main_>_label]:[gap:5px] [&>_main_>_label_span]:[background:var(--muted)] [&>_main_>_label_span]:[border:1px_solid_var(--border)] [&>_main_>_label_span]:rounded-sm [&>_main_>_label_span]:[color:var(--muted-foreground)] [&>_main_>_label_span]:[font-weight:400] [&>_main_>_label_span]:[min-height:30px] [&>_main_>_label_span]:[padding:6px_8px] [&>_main_fieldset]:[border:1px_solid_var(--border)] [&>_main_fieldset]:rounded-lg [&>_main_fieldset]:[display:flex] [&>_main_fieldset]:[flex-direction:column] [&>_main_fieldset]:[gap:9px] [&>_main_fieldset]:[padding:10px_12px_12px] [&>_main_legend]:[color:var(--muted-foreground)] [&>_main_legend]:[padding:0_4px] [&>_main_p[role=alert]]:[color:var(--destructive)] [&>_main_p[role=alert]]:[margin:0] [&>_footer]:[border-top:1px_solid_var(--border)] [&>_footer]:[display:flex] [&>_footer]:[gap:8px] [&>_footer]:[justify-content:flex-end] [&>_footer]:[padding:10px_12px]",
  favorite: "favorite [color:var(--bookmark)] [fill:var(--bookmark)]",
  filterSpacer: "filterSpacer [flex:1]",
  focusedDiffViewer:
    "focusedDiffViewer [background:var(--card)] rounded-lg [inset:56px_30px_18px_31px] [position:fixed] [z-index:45]",
  graphCanvas:
    "graphCanvas [left:2px] [pointer-events:none] [position:absolute] [top:0] [width:34px] [z-index:2]",
  gitBranchesPopup:
    "gitBranchesPopup [background:var(--popover)] [border:1px_solid_var(--input)] rounded-lg [box-shadow:var(--shadow-lg)] [display:grid] [grid-template-rows:36px_minmax(120px,_auto)] [left:0] [max-height:min(520px,_calc(100vh_-_70px))] [min-width:368px] [overflow:hidden] [position:absolute] [top:31px] [z-index:100]",
  gitBranchesSearch:
    "gitBranchesSearch [align-items:center] [border-bottom:1px_solid_var(--border)] [display:grid] [gap:5px] [grid-template-columns:minmax(0,_1fr)_auto] [padding:4px_5px] [&>_label]:[align-items:center] [&>_label]:[background:var(--secondary)] [&>_label]:[border:1px_solid_var(--border)] [&>_label]:rounded-sm [&>_label]:[display:flex] [&>_label]:[gap:5px] [&>_label]:[padding:0_6px] [&>_label:focus-within]:[border-color:var(--primary)] [&_input]:[background:transparent] [&_input]:[border:0] [&_input]:[height:25px] [&_input]:[min-width:0] [&_input]:[outline:0] [&_input]:[width:100%] [&_[role=toolbar]]:[display:flex] [&_[role=toolbar]_button]:[align-items:center] [&_[role=toolbar]_button]:[background:transparent] [&_[role=toolbar]_button]:[display:flex] [&_[role=toolbar]_button]:[height:26px] [&_[role=toolbar]_button]:[justify-content:center] [&_[role=toolbar]_button]:[width:26px]",
  gitBranchesList:
    "gitBranchesList [min-height:0] [overflow:auto] [padding:4px] [&_[role=separator]]:[border-top:1px_solid_var(--border)] [&_[role=separator]]:[height:5px] [&_[role=separator]]:[margin-top:4px] [&_[role=treeitem]]:[align-items:center] [&_[role=treeitem]]:[background:transparent] [&_[role=treeitem]]:rounded-sm [&_[role=treeitem]]:[display:grid] [&_[role=treeitem]]:[gap:6px] [&_[role=treeitem]]:[grid-template-columns:17px_minmax(0,_1fr)_auto_auto] [&_[role=treeitem]]:[height:27px] [&_[role=treeitem]]:[padding:0_7px] [&_[role=treeitem]]:[text-align:left] [&_[role=treeitem]]:[width:100%] [&_[role=treeitem]:hover]:[background:var(--muted)] [&_[role=treeitem][aria-selected=true]]:[background:var(--accent)] [&_[role=group]_[role=treeitem]]:[padding-left:25px] [&_[data-branch-group=true]]:[font-weight:600] [&_kbd]:[color:var(--disabled-foreground)] [&_kbd]:[font:inherit] [&_small]:[color:var(--disabled-foreground)] [&_small]:[font-size:10px] [&>_p]:[color:var(--muted-foreground)] [&>_p]:[padding:20px] [&>_p]:[text-align:center]",
  findResultsPanel:
    "findResultsPanel [display:grid] [grid-template-rows:32px_minmax(0,_1fr)] [height:100%] [min-height:0] [&>_header]:[align-items:center] [&>_header]:[border-bottom:1px_solid_var(--border)] [&>_header]:[display:flex] [&>_header]:[gap:7px] [&>_header]:[padding:0_7px] [&>_header_strong]:[font-size:11px] [&>_header_span]:[color:var(--muted-foreground)] [&>_header_span]:[flex:1] [&>_header_button]:[background:var(--secondary)] [&>_header_button]:[border:1px_solid_var(--border)] [&>_header_button]:[height:25px] [&>_header_button]:[padding:0_7px] [&>_ul]:[min-height:0] [&>_ul]:[overflow:auto] [&>_ul]:[padding:4px] [&_li]:[min-height:37px] [&_li_code]:[color:var(--disabled-foreground)] [&_li_code]:[font-size:9px]",
  gitBranchSelectedActions:
    "gitBranchSelectedActions [border-top:1px_solid_var(--border)] [display:flex] [flex-wrap:wrap] [gap:3px] [padding:4px_5px] [&_button]:[background:transparent] [&_button]:[font-size:10px] [&_button]:[height:25px] [&_button]:[padding:0_6px]",
  gitBranchComparison:
    "gitBranchComparison [align-items:center] [background:var(--muted)] [border-top:1px_solid_var(--border)] [display:flex] [font-size:10px] [gap:8px] [padding:5px_8px] [&_span]:[color:var(--muted-foreground)]",
  gitConsolePanel:
    "gitConsolePanel [display:grid] [grid-template-rows:31px_minmax(0,_1fr)] [height:100%] [min-height:0] [&>_header]:[align-items:center] [&>_header]:[border-bottom:1px_solid_var(--border)] [&>_header]:[display:flex] [&>_header]:[gap:5px] [&>_header]:[padding:0_6px] [&>_header_span]:[color:var(--muted-foreground)] [&>_header_i]:[flex:1] [&>_header_button]:[background:transparent] [&>_header_button]:[font-size:10px] [&>_header_button]:[height:24px] [&>_header_button]:[padding:0_6px]",
  gitConsoleList:
    "gitConsoleList [min-height:0] [overflow:auto] [&_article]:[border-bottom:1px_solid_var(--border)] [&_article[aria-selected=true]]:[background:var(--accent)] [&_article>_button]:[align-items:center] [&_article>_button]:[background:transparent] [&_article>_button]:[display:grid] [&_article>_button]:[gap:8px] [&_article>_button]:[grid-template-columns:16px_minmax(0,_1fr)_80px_62px] [&_article>_button]:[height:27px] [&_article>_button]:[padding:0_7px] [&_article>_button]:[text-align:left] [&_article>_button]:[width:100%] [&_article_code]:[overflow:hidden] [&_article_code]:[text-overflow:ellipsis] [&_article_code]:[white-space:nowrap] [&_article_small]:[color:var(--disabled-foreground)] [&_article_small]:[font-size:9px] [&_article_pre]:[background:var(--muted)] [&_article_pre]:[border-top:1px_solid_var(--border)] [&_article_pre]:[font-family:var(--font-family-code)] [&_article_pre]:[font-size:10px] [&_article_pre]:[margin:0] [&_article_pre]:[max-height:180px] [&_article_pre]:[overflow:auto] [&_article_pre]:[padding:7px_30px] [&_article_pre]:[white-space:pre-wrap]",
  headRow:
    "headRow [align-items:center] [border-bottom:1px_solid_var(--border)] [display:flex] [gap:6px] [padding:0_10px] [&.muted]:[color:var(--disabled-foreground)] [&.muted]:[font-size:10px]",
  historyList:
    "historyList [&_article:hover]:[background:var(--muted)] [&_span]:[color:var(--disabled-foreground)] [&_time]:[color:var(--disabled-foreground)] [&_article]:[align-items:center] [&_article]:[border-bottom:1px_solid_var(--border)] [&_article]:[display:grid] [&_article]:[gap:10px] [&_article]:[grid-template-columns:75px_minmax(200px,_1fr)_130px_170px] [&_article]:[min-height:38px] [&_article]:[padding:0_12px]",
  hostingAccountBar:
    "hostingAccountBar [align-items:center] [display:flex] [gap:8px] [background:var(--muted)] [border-bottom:1px_solid_var(--border)] [min-height:52px] [padding:7px_11px] [&_label]:[color:var(--muted-foreground)] [&_label]:[display:flex] [&_label]:[flex-direction:column] [&_label]:[font-size:11px] [&_label]:[gap:3px] [&_label:nth-child(2)]:[flex:1]",
  hostingAccountMeta:
    "hostingAccountMeta [align-items:center] [display:flex] [gap:8px] [border-top:1px_solid_var(--border)] [color:var(--muted-foreground)] [margin-top:9px] [padding-top:8px] [&>_span:first-child]:[flex:1]",
  hostingColumns:
    "hostingColumns [display:grid] [flex:1] [grid-template-columns:minmax(230px,_34%)_minmax(0,_1fr)] [min-height:0]",
  hostingComposer:
    "hostingComposer [&>_footer]:[align-items:center] [&>_footer]:[display:flex] [&>_footer]:[gap:8px] [&_label]:[color:var(--muted-foreground)] [&_label]:[display:flex] [&_label]:[flex-direction:column] [&_label]:[font-size:11px] [&_label]:[gap:3px] [background:var(--secondary)] [border-bottom:1px_solid_var(--border)] [display:flex] [flex-direction:column] [gap:8px] [padding:11px] [&_textarea]:[min-height:64px] [&_textarea]:[resize:vertical] [&>_div]:[align-items:end] [&>_div]:[display:grid] [&>_div]:[gap:8px] [&>_div]:[grid-template-columns:1fr_1fr_auto] [&>_footer]:[justify-content:flex-end]",
  hostingConnect:
    "hostingConnect [border-bottom:1px_solid_var(--border)] [padding:8px_11px] [&_summary]:[color:var(--muted-foreground)] [&_summary]:[cursor:default] [&_summary]:[font-weight:600]",
  hostingDetail:
    "hostingDetail [&>_header]:[align-items:center] [&>_header]:[display:flex] [&>_header]:[gap:8px] [min-height:0] [overflow:auto] [&_small]:[color:var(--disabled-foreground)] [&>_header]:[border-bottom:1px_solid_var(--border)] [&>_header]:[padding:9px_11px] [&>_header_>_div]:[display:flex] [&>_header_>_div]:[flex:1] [&>_header_>_div]:[flex-direction:column] [&>_header_>_div]:[min-width:0] [&>_header_small]:[overflow:hidden] [&>_header_small]:[text-overflow:ellipsis] [&>_header_small]:[white-space:nowrap] [&_h3]:[color:var(--muted-foreground)] [&_h3]:[font-size:12px] [&_h3]:[margin:0] [&_h3]:[padding:10px_11px_6px]",
  hostingFile:
    "hostingFile [border-top:1px_solid_var(--border)] [padding:8px_11px] [&>_label]:[float:right] [&>_strong]:[display:block] [&>_small]:[display:block] [&_pre]:[background:var(--muted)] [&_pre]:[border:1px_solid_var(--border)] [&_pre]:rounded-lg [&_pre]:[font-size:12px] [&_pre]:[max-height:280px] [&_pre]:[overflow:auto] [&_pre]:[padding:9px]",
  hostingFormGrid:
    "hostingFormGrid [&_label]:[color:var(--muted-foreground)] [&_label]:[display:flex] [&_label]:[flex-direction:column] [&_label]:[font-size:11px] [&_label]:[gap:3px] [align-items:end] [display:grid] [gap:8px] [grid-template-columns:110px_minmax(190px,_1fr)_minmax(190px,_1fr)_auto] [padding-top:9px]",
  hostingList:
    "hostingList [min-height:0] [overflow:auto] [border-right:1px_solid_var(--border)] [&>_button]:[align-items:stretch] [&>_button]:[background:transparent] [&>_button]:[border:0] [&>_button]:[border-bottom:1px_solid_var(--border)] [&>_button]:rounded-none [&>_button]:[display:flex] [&>_button]:[flex-direction:column] [&>_button]:[gap:4px] [&>_button]:[padding:10px_11px] [&>_button]:[text-align:left] [&>_button]:[width:100%] [&_small]:[color:var(--disabled-foreground)]",
  hostingListToolbar:
    "hostingListToolbar [align-items:center] [background:var(--muted)] [border-bottom:1px_solid_var(--border)] [display:flex] [gap:5px] [padding:5px] [position:sticky] [top:0] [z-index:2] [&>_label]:[align-items:center] [&>_label]:[background:var(--secondary)] [&>_label]:[border:1px_solid_var(--border)] [&>_label]:rounded-sm [&>_label]:[display:flex] [&>_label]:[flex:1] [&>_label]:[gap:5px] [&>_label]:[padding:0_6px] [&>_label_input]:[background:transparent] [&>_label_input]:[border:0] [&>_label_input]:[min-width:0] [&>_label_input]:[outline:0] [&>_label_input]:[padding:0] [&>_label_input]:[width:100%] [&>_select]:[width:78px]",
  hostingPanel:
    "hostingPanel [display:flex] [flex-direction:column] [height:100%] [min-height:0] [&_input]:[background:var(--secondary)] [&_input]:[border:1px_solid_var(--border)] [&_input]:[min-height:29px] [&_input]:[padding:4px_8px] [&_select]:[background:var(--secondary)] [&_select]:[border:1px_solid_var(--border)] [&_select]:[min-height:29px] [&_select]:[padding:4px_8px] [&_textarea]:[background:var(--secondary)] [&_textarea]:[border:1px_solid_var(--border)] [&_textarea]:[min-height:29px] [&_textarea]:[padding:4px_8px] [&_button]:[align-items:center] [&_button]:[background:var(--secondary)] [&_button]:[border:1px_solid_var(--border)] [&_button]:[display:inline-flex] [&_button]:[gap:5px] [&_button]:[min-height:29px] [&_button]:[padding:0_9px]",
  hostingProgress:
    "hostingProgress [border-bottom:1px_solid_var(--border)] [padding:7px_12px] [color:var(--primary)]",
  hostingReviewBar:
    "hostingReviewBar [align-items:center] [display:flex] [gap:8px] [border-bottom:1px_solid_var(--border)] [padding:8px_11px] [&_textarea]:[flex:1] [&_textarea]:[min-height:52px] [&_textarea]:[resize:vertical]",
  hostingTimeline:
    "hostingTimeline [border-top:1px_solid_var(--border)] [padding:8px_11px] [&_p]:[line-height:1.45] [&_p]:[margin:5px_0_0] [&_p]:[white-space:pre-wrap] [&_small]:[float:right]",
  hostingDiscussionComposer:
    "hostingDiscussionComposer [align-items:flex-end] [border-top:1px_solid_var(--border)] [display:flex] [gap:8px] [padding:8px_11px] [&_textarea]:[flex:1] [&_textarea]:[min-height:54px] [&_textarea]:[resize:vertical]",
  ignoreEditors:
    "ignoreEditors [display:grid] [gap:10px] [grid-template-columns:1fr_1fr] [padding:10px_11px] [&_label]:[color:var(--muted-foreground)] [&_label]:[display:flex] [&_label]:[flex-direction:column] [&_label]:[font-size:11px] [&_label]:[gap:5px] [&_textarea]:[background:var(--muted)] [&_textarea]:[border:1px_solid_var(--border)] [&_textarea]:rounded-lg [&_textarea]:[color:var(--foreground)] [&_textarea]:[font-family:var(--font-family-code)] [&_textarea]:[font-size:12px] [&_textarea]:[min-height:150px] [&_textarea]:[padding:8px] [&_textarea]:[resize:vertical] max-[1120px]:[grid-template-columns:1fr]",
  imageDiff:
    "imageDiff [display:grid] [grid-template-rows:auto_minmax(0,_1fr)] [height:100%] [min-height:0] [background:var(--card)] [&_figcaption]:[position:relative] [&_figcaption]:[z-index:2] [&_figcaption]:[padding:7px_10px] [&_figcaption]:[color:var(--muted-foreground)] [&_figcaption]:[background:var(--muted)] [&_figcaption]:[border-bottom:1px_solid_var(--border)] [&_figcaption]:[font-size:11px]",
  imageDiffOverlay:
    "imageDiffOverlay [display:grid] [grid-template-rows:auto_minmax(0,_1fr)] [min-width:0] [min-height:0] [margin:0] [background-color:var(--card)] [background-image:linear-gradient(45deg,_var(--muted)_25%,_transparent_25%),_linear-gradient(-45deg,_var(--muted)_25%,_transparent_25%),_linear-gradient(45deg,_transparent_75%,_var(--muted)_75%),_linear-gradient(-45deg,_transparent_75%,_var(--muted)_75%)] [background-size:18px_18px] [background-position:0_0,_0_9px,_9px_-9px,_-9px_0] [&>_div]:[position:relative] [&>_div]:[min-height:0] [&_img]:[position:absolute] [&_img]:[inset:0] [&_img]:[width:100%] [&_img]:[height:100%] [&_img]:[object-fit:contain] [&_img]:[padding:16px]",
  imageDiffPair:
    "imageDiffPair [display:grid] [grid-template-columns:repeat(2,_minmax(0,_1fr))] [min-height:0] [&_figure]:[display:grid] [&_figure]:[grid-template-rows:auto_minmax(0,_1fr)] [&_figure]:[min-width:0] [&_figure]:[min-height:0] [&_figure]:[margin:0] [&_figure]:[background-color:var(--card)] [&_figure]:[background-image:linear-gradient(45deg,_var(--muted)_25%,_transparent_25%),_linear-gradient(-45deg,_var(--muted)_25%,_transparent_25%),_linear-gradient(45deg,_transparent_75%,_var(--muted)_75%),_linear-gradient(-45deg,_transparent_75%,_var(--muted)_75%)] [&_figure]:[background-size:18px_18px] [&_figure]:[background-position:0_0,_0_9px,_9px_-9px,_-9px_0] [&_figure_+_figure]:[border-left:1px_solid_var(--border)] [&_figure_>_img]:[width:100%] [&_figure_>_img]:[height:100%] [&_figure_>_img]:[min-height:180px] [&_figure_>_img]:[object-fit:contain] [&_figure_>_img]:[padding:16px] [&_figure_>_div]:[width:100%] [&_figure_>_div]:[height:100%] [&_figure_>_div]:[min-height:180px] [&_figure_>_div]:[object-fit:contain] [&_figure_>_div]:[padding:16px] [&_figure_>_div]:[display:grid] [&_figure_>_div]:[place-items:center] [&_figure_>_div]:[color:var(--muted-foreground)] max-[960px]:[grid-template-columns:1fr] max-[960px]:[overflow:auto] max-[960px]:[&_figure_+_figure]:[border-left:0] max-[960px]:[&_figure_+_figure]:[border-top:1px_solid_var(--border)]",
  imageDiffToolbar:
    "imageDiffToolbar [display:flex] [min-height:36px] [align-items:center] [justify-content:space-between] [gap:12px] [padding:5px_10px] [border-bottom:1px_solid_var(--border)] [background:var(--muted)] [&>_div]:[display:flex] [&>_div]:[align-items:center] [&>_div]:[gap:6px] [&>_label]:[display:flex] [&>_label]:[align-items:center] [&>_label]:[gap:6px] [&_input[type=range]]:[width:120px]",
  imageViewer:
    "imageViewer [align-items:center] [display:flex] [flex-direction:column] [gap:12px] [height:100%] [justify-content:center] [margin:0] [overflow:auto] [padding:20px] [&_img]:[background:var(--muted)] [&_img]:[box-shadow:var(--shadow-xs)] [&_img]:[max-height:calc(100%_-_54px)] [&_img]:[max-width:100%] [&_img]:[object-fit:contain] [&_figcaption]:[align-items:center] [&_figcaption]:[color:var(--muted-foreground)] [&_figcaption]:[display:flex] [&_figcaption]:[gap:9px] [&_figcaption_strong]:[color:var(--foreground)] [&_button]:[background:var(--muted)] [&_button]:[border:1px_solid_var(--border)] [&_button]:rounded-sm [&_button]:[height:28px] [&_button]:[padding:0_9px]",
  inlineCheck:
    "inlineCheck [align-items:center] [flex-direction:row]! [min-height:29px] [&_input]:[min-height:auto]",
  inspectorContent: "inspectorContent [min-height:0] [overflow:auto]",
  inspectorEmbedded:
    "inspectorEmbedded [display:grid] [grid-template-rows:38px_minmax(0,_1fr)] [height:100%] [min-height:0] [overflow:hidden] [&>_nav]:[align-items:center] [&>_nav]:[border-bottom:1px_solid_var(--border)]",
  inspectorTree:
    "inspectorTree [&>_button]:[align-items:center] [&>_button]:[background:transparent] [&>_button]:[display:grid] [&>_button]:[gap:8px] [&>_button]:[grid-template-columns:18px_minmax(180px,_1fr)_70px_90px_70px] [&>_button]:[height:29px] [&>_button]:[padding:0_12px] [&>_button]:[text-align:left] [&>_button]:[width:100%] [&>_button:hover]:[background:var(--muted)] [&_small]:[color:var(--disabled-foreground)] [&_code]:[color:var(--disabled-foreground)]",
  loadingEditorTabs:
    "loadingEditorTabs [align-items:center] [border-bottom:1px_solid_var(--border)] [display:flex] [height:29px] [left:0] [padding:0_5px] [position:absolute] [right:0] [top:0] [&>_span]:[align-items:center] [&>_span]:[background:var(--accent)] [&>_span]:rounded-sm [&>_span]:[color:var(--foreground)] [&>_span]:[display:flex] [&>_span]:[gap:5px] [&>_span]:[height:24px] [&>_span]:[padding:0_8px]",
  logViewOptions:
    "logViewOptions [display:grid] [gap:3px] [padding:5px] [&>_strong]:[border-top:1px_solid_var(--border)] [&>_strong]:[color:var(--muted-foreground)] [&>_strong]:[font-size:10px] [&>_strong]:[margin:4px_5px_1px] [&>_strong]:[padding-top:6px]",
  logFilters:
    "logFilters [align-items:center] [background:var(--secondary)] [border-bottom:1px_solid_var(--border)] [display:flex] [gap:3px] [overflow:hidden] [padding:0_5px] [&>_label]:[flex:none]",
  logFooter: "logFooter [display:none]",
  logPane:
    "logPane [background:var(--card)] [min-height:0] [min-width:0] [display:grid] [grid-template-rows:26px_minmax(0,_1fr)_0]",
  logSearchControls:
    "logSearchControls [flex:0_1_148px] [height:28px] [max-width:148px] [min-width:118px] [position:relative] [&_input]:[padding-right:43px]! [&>_button]:[position:absolute] [&>_button]:[top:2px] [&>_button:nth-of-type(1)]:[right:21px] [&>_button:nth-of-type(2)]:[right:1px]",
  mainPanes:
    "mainPanes [display:grid] [grid-template-columns:29px_minmax(0,_1fr)_var(--details-pane-width,_300px)] [height:100%] [min-height:0] [min-width:0] max-[900px]:[grid-template-columns:29px_minmax(0,_1fr)] max-[900px]:[&>_*:last-child]:[display:none]",
  activeWorkspace:
    "activeWorkspace [background:var(--card)] rounded-lg [display:grid] [min-height:0] [min-width:0] [overflow:hidden] [padding-top:26px] [position:relative]",
  activeWorkspaceNoTabs: "activeWorkspaceNoTabs [padding-top:0]",
  projectToolOpen:
    "projectToolOpen [grid-template-columns:minmax(260px,_var(--side-tool-window-width,_386px))_minmax(0,_1fr)]",
  projectToolWindow:
    "projectToolWindow [background:var(--card)] rounded-lg [display:grid] [grid-template-rows:26px_minmax(0,_1fr)] [min-height:0] [min-width:0] [overflow:hidden] [position:relative] [&>_.verticalResizeHandle]:[right:0]",
  bookmarksToolWindow:
    "bookmarksToolWindow [background:var(--card)] rounded-xl [display:grid] [grid-template-rows:30px_minmax(0,_1fr)] [min-height:0] [min-width:0] [overflow:hidden]",
  bookmarksTree: "bookmarksTree [min-height:0] [overflow:auto] [padding:3px_0]",
  bookmarkGroupRow:
    "bookmarkGroupRow [align-items:center] [display:grid] [grid-template-columns:minmax(0,_1fr)_22px_22px_22px] [min-width:0] [&>_button]:[align-items:center] [&>_button]:[background:transparent] [&>_button]:[border:0] [&>_button]:[color:var(--muted-foreground)] [&>_button]:[display:flex] [&>_button]:[height:24px] [&>_button]:[justify-content:center] [&>_button]:[min-width:0] [&>_button]:[padding:0] [&>_button:hover]:[background:var(--overlay-hover)] [&>_button:first-child]:[gap:4px] [&>_button:first-child]:[justify-content:flex-start] [&>_button:first-child]:[padding:0_5px] [&>_button:first-child>_svg:first-child]:[transition:transform_100ms] [&>_button:first-child[aria-expanded=true]>_svg:first-child]:[transform:rotate(90deg)] [&_strong]:[color:var(--foreground)] [&_strong]:[font-size:11px] [&_strong]:[overflow:hidden] [&_strong]:[text-overflow:ellipsis] [&_strong]:[white-space:nowrap] [&_small]:[background:var(--muted)] [&_small]:rounded-xs [&_small]:[font-size:9px] [&_small]:[margin-left:3px] [&_small]:[padding:1px_4px]",
  bookmarkRow:
    "bookmarkRow [align-items:center] [display:grid] [grid-template-columns:minmax(0,_1fr)_20px_20px_20px] [height:31px] [min-width:0] [&>_button]:[align-items:center] [&>_button]:[background:transparent] [&>_button]:[border:0] [&>_button]:[color:var(--muted-foreground)] [&>_button]:[display:flex] [&>_button]:[height:28px] [&>_button]:[justify-content:center] [&>_button]:[padding:0] [&>_button:hover]:[background:var(--overlay-hover)] [&>_button:first-child]:[display:grid] [&>_button:first-child]:[gap:0_5px] [&>_button:first-child]:[grid-template-columns:17px_minmax(0,_1fr)] [&>_button:first-child]:[grid-template-rows:15px_12px] [&>_button:first-child]:[justify-content:stretch] [&>_button:first-child]:[padding:1px_5px_1px_16px] [&>_button:first-child]:[text-align:left] [&>_button:first-child]:[width:100%] [&>_button:first-child[aria-selected=true]]:[background:var(--accent)] [&>_button:first-child>_span]:[align-items:center] [&>_button:first-child>_span]:[color:var(--primary)] [&>_button:first-child>_span]:[display:flex] [&>_button:first-child>_span]:[font-size:10px] [&>_button:first-child>_span]:[font-weight:700] [&>_button:first-child>_span]:[grid-row:1_/_3] [&_strong]:[color:var(--foreground)] [&_strong]:[font-size:11px] [&_strong]:[font-weight:500] [&_strong]:[overflow:hidden] [&_strong]:[text-overflow:ellipsis] [&_strong]:[white-space:nowrap] [&_small]:[color:var(--disabled-foreground)] [&_small]:[font-size:9px] [&_small]:[overflow:hidden] [&_small]:[text-overflow:ellipsis] [&_small]:[white-space:nowrap] [&>_button:nth-child(3)>_svg]:[transform:rotate(180deg)]",
  bookmarkFileGroup:
    "bookmarkFileGroup [&>_div:first-child]:[align-items:center] [&>_div:first-child]:[color:var(--muted-foreground)] [&>_div:first-child]:[display:grid] [&>_div:first-child]:[gap:5px] [&>_div:first-child]:[grid-template-columns:14px_minmax(0,_1fr)_auto] [&>_div:first-child]:[height:22px] [&>_div:first-child]:[padding:0_7px_0_18px] [&>_div:first-child>_strong]:[font-size:10px] [&>_div:first-child>_strong]:[font-weight:500] [&>_div:first-child>_strong]:[overflow:hidden] [&>_div:first-child>_strong]:[text-overflow:ellipsis] [&>_div:first-child>_strong]:[white-space:nowrap] [&>_div:first-child>_small]:[font-size:9px]",
  bookmarkOptions: "bookmarkOptions [display:grid] [gap:2px] [padding:5px]",
  bookmarksPopup:
    "bookmarksPopup [display:grid] [grid-template-rows:auto_minmax(180px,_1fr)] [max-height:min(640px,_calc(100vh_-_82px))] [min-height:330px] [&>_[role=listbox]]:[min-height:0] [&>_[role=listbox]]:[overflow:auto]",
  bookmarkMnemonicDialog:
    "bookmarkMnemonicDialog [display:grid] [gap:12px] [padding-bottom:12px] [&>_*:not(:first-child)]:[margin-left:12px] [&>_*:not(:first-child)]:[margin-right:12px] [&>_p]:[color:var(--muted-foreground)] [&>_p]:[font-size:10px] [&>_p]:[margin-bottom:0] [&>_p]:[margin-top:-3px] [&>_footer]:[display:flex] [&>_footer]:[gap:7px] [&>_footer]:[justify-content:flex-end]",
  bookmarkMnemonicGrid:
    "bookmarkMnemonicGrid [display:grid] [gap:4px] [grid-template-columns:repeat(10,_1fr)] [&>_button]:[background:var(--muted)] [&>_button]:[border:1px_solid_transparent] [&>_button]:rounded-sm [&>_button]:[color:var(--foreground)] [&>_button]:[font-family:var(--font-family-code)] [&>_button]:[font-size:11px] [&>_button]:[height:28px] [&>_button:hover]:[background:var(--overlay-hover)] [&>_button[aria-selected=true]]:[background:var(--accent)] [&>_button[aria-selected=true]]:[border-color:var(--primary)] [&>_button[data-assigned=true]]:[color:var(--disabled-foreground)] [&>_button[data-assigned=true]]:[text-decoration:underline]",
  bookmarkGroupSelectDialog:
    "bookmarkGroupSelectDialog [display:grid] [grid-template-rows:auto_minmax(110px,_260px)_auto_auto_auto] [gap:10px] [padding-bottom:12px] [&>_*:not(:first-child)]:[margin-left:12px] [&>_*:not(:first-child)]:[margin-right:12px] [&>_[role=listbox]]:[border:1px_solid_var(--border)] [&>_[role=listbox]]:rounded-sm [&>_[role=listbox]]:[min-height:0] [&>_[role=listbox]]:[overflow:auto] [&>_p]:[color:var(--muted-foreground)] [&>_p]:[font-size:10px] [&>_p]:[margin-bottom:0] [&>_p]:[margin-top:-5px] [&>_footer]:[display:flex] [&>_footer]:[gap:7px] [&>_footer]:[justify-content:flex-end]",
  bookmarkGroupCreateDialog:
    "bookmarkGroupCreateDialog [display:grid] [gap:10px] [padding-bottom:12px] [&>_*:not(:first-child)]:[margin-left:12px] [&>_*:not(:first-child)]:[margin-right:12px] [&>_p]:[color:var(--muted-foreground)] [&>_p]:[font-size:10px] [&>_p]:[margin-bottom:0] [&>_p]:[margin-top:-5px] [&>_footer]:[display:flex] [&>_footer]:[gap:7px] [&>_footer]:[justify-content:flex-end]",
  quickSwitchSchemeDialog:
    "quickSwitchSchemeDialog [display:grid] [gap:10px] [grid-template-columns:1fr_1fr] [padding-bottom:12px] [&>_*:not(:first-child)]:[margin-left:12px] [&>_*:not(:first-child)]:[margin-right:12px] [&>_header]:[grid-column:1_/_3] [&>_div:first-of-type]:[grid-column:1_/_3] [&_h3]:[font-size:11px] [&_h3]:[margin:0_0_5px] [&_select]:[background:var(--secondary)] [&_select]:[border:1px_solid_var(--border)] [&_select]:rounded-sm [&_select]:[color:var(--foreground)] [&_select]:[height:28px] [&_select]:[width:100%] [&>_footer]:[border-top:1px_solid_var(--border)] [&>_footer]:[display:flex] [&>_footer]:[grid-column:1_/_3] [&>_footer]:[justify-content:flex-end] [&>_footer]:[margin-left:0]! [&>_footer]:[margin-right:0]! [&>_footer]:[padding:10px_12px_0]",
  projectToolHeader:
    "projectToolHeader [align-items:center] [border-bottom:1px_solid_var(--border)] [display:flex] [padding:0_3px_0_6px] [&>_span]:[flex:1] [&>_button]:[align-items:center] [&>_button]:[background:transparent] [&>_button]:rounded-sm [&>_button]:[color:var(--muted-foreground)] [&>_button]:[display:flex] [&>_button]:[height:24px] [&>_button]:[justify-content:center] [&>_button]:[width:24px] [&>_button:first-child]:[color:var(--foreground)] [&>_button:first-child]:[font-size:12px] [&>_button:first-child]:[padding:0_4px] [&>_button:first-child]:[width:auto] [&>_button:hover]:[background:var(--muted)] [&>_button:hover]:[color:var(--foreground)]",
  projectSwitcherActions:
    "projectSwitcherActions [border-bottom:1px_solid_var(--border)] [display:grid] [padding:5px] [&_button]:[align-items:center] [&_button]:[background:transparent] [&_button]:rounded-sm [&_button]:[display:flex] [&_button]:[gap:8px] [&_button]:[height:30px] [&_button]:[padding:0_8px] [&_button:hover]:[background:var(--muted)] [&_button[aria-selected=true]]:[background:var(--accent)]",
  projectSwitcherPopup:
    "projectSwitcherPopup [background:var(--popover)] [border:1px_solid_var(--input)] rounded-lg [box-shadow:var(--shadow-lg)] [left:0] [max-height:min(540px,_calc(100vh_-_62px))] [min-width:368px] [overflow:auto] [padding:0_0_5px] [position:absolute] [top:calc(100%_+_2px)] [z-index:80] [&_[data-project-section]]:[border-top:1px_solid_var(--border)] [&_[data-project-section]]:[color:var(--muted-foreground)] [&_[data-project-section]]:[display:block] [&_[data-project-section]]:[font-size:10px] [&_[data-project-section]]:[font-weight:600] [&_[data-project-section]]:[padding:8px_11px_4px] [&>_p]:[color:var(--destructive)] [&>_p]:[font-size:10px] [&>_p]:[margin:5px_9px]",
  projectSwitcherRow:
    "projectSwitcherRow [align-items:center] [background:transparent] [display:grid] [gap:8px] [grid-template-columns:24px_minmax(0,_1fr)_16px] [min-height:45px] [padding:5px_8px] [text-align:left] [width:100%] [&:hover]:[background:var(--muted)] [&[aria-selected=true]]:[background:var(--accent)] [&>_span:nth-child(2)]:[display:flex] [&>_span:nth-child(2)]:[flex-direction:column] [&>_span:nth-child(2)]:[min-width:0] [&_b]:[font-weight:600] [&_b]:[overflow:hidden] [&_b]:[text-overflow:ellipsis] [&_b]:[white-space:nowrap] [&_small]:[color:var(--disabled-foreground)] [&_small]:[font-size:10px] [&_small]:[overflow:hidden] [&_small]:[text-overflow:ellipsis] [&_small]:[white-space:nowrap]",
  projectRootLabel:
    "projectRootLabel [align-items:center] [display:flex]! [gap:5px] [&_strong]:[font-weight:600] [&_small]:[color:var(--disabled-foreground)] [&_small]:[font-size:10px] [&_small]:[overflow:hidden] [&_small]:[text-overflow:ellipsis] [&_small]:[white-space:nowrap]",
  projectTree: "projectTree [min-height:0] [overflow:auto] [padding:3px_0]",
  projectTreeRow:
    "projectTreeRow [align-items:center] [background:transparent] [border:0] [color:var(--foreground)] [display:grid] [font-size:12px] [gap:4px] [grid-template-columns:14px_16px_minmax(0,_1fr)_auto] [height:20px] [padding:0_7px_0_calc(7px_+_var(--tree-depth)_*_14px)] [text-align:left] [width:100%] [&:hover]:[background:var(--overlay-hover)] [&[aria-selected=true]]:[background:var(--accent)] [&>_span:nth-child(3)]:[overflow:hidden] [&>_span:nth-child(3)]:[text-overflow:ellipsis] [&>_span:nth-child(3)]:[white-space:nowrap] [&_small]:[color:var(--disabled-foreground)] [&_small]:[font-size:9px] [&_em]:[color:var(--primary)] [&_em]:[font-size:10px] [&_em]:[font-style:normal] [&_em[data-status=untracked]]:[color:var(--success)] [&_em[data-status=deleted]]:[color:var(--destructive)] [&_em[data-status=conflicted]]:[color:var(--destructive)]",
  projectTreeIndent: "projectTreeIndent [display:block] [height:12px] [width:12px]",
  projectFolderIcon: "projectFolderIcon [color:var(--project-folder)]",
  projectFileIcon: "projectFileIcon [color:var(--muted-foreground)]",
  projectScratches:
    "projectScratches [align-items:center] [background:transparent] [color:var(--muted-foreground)] [display:flex] [gap:4px] [height:22px] [padding:0_8px] [text-align:left]",
  projectScratchFile:
    "projectScratchFile [align-items:center] [background:transparent] [display:grid] [gap:4px] [grid-template-columns:12px_16px_minmax(0,_1fr)] [height:22px] [padding:0_8px] [text-align:left] [width:100%] [&:hover]:[background:var(--muted)] [&:focus]:[background:var(--accent)] [&>_span:last-child]:[overflow:hidden] [&>_span:last-child]:[text-overflow:ellipsis] [&>_span:last-child]:[white-space:nowrap]",
  projectViewOptions:
    "projectViewOptions [display:grid] [gap:3px] [padding:5px] [&>_strong]:[color:var(--muted-foreground)] [&>_strong]:[font-size:10px] [&>_strong]:[font-weight:600] [&>_strong]:[margin:5px_6px_2px] [&>_strong:not(:first-child)]:[border-top:1px_solid_var(--border)] [&>_strong:not(:first-child)]:[padding-top:7px]",
  changesViewOptions:
    "changesViewOptions [display:grid] [gap:3px] [padding:5px] [&>_strong]:[color:var(--muted-foreground)] [&>_strong]:[font-size:10px] [&>_strong]:[font-weight:600] [&>_strong]:[margin:5px_6px_2px] [&>_strong:not(:first-child)]:[border-top:1px_solid_var(--border)] [&>_strong:not(:first-child)]:[padding-top:7px]",
  diffPreviewHidden:
    "diffPreviewHidden [align-items:center] [background:var(--card)] [color:var(--muted-foreground)] [display:flex] [flex-direction:column] [gap:7px] [justify-content:center] [min-height:0] [&>_p]:[margin:0]",
  startupWorkspace:
    "startupWorkspace [grid-row:2_/_-1] [min-height:0] [background:var(--card)] [display:grid] [grid-template-rows:auto_minmax(0,_1fr)] [overflow:hidden]",
  managementRow:
    "managementRow [&>_button]:[align-items:center] [&>_button]:[background:var(--card)] [&>_button]:[border:1px_solid_var(--border)] [&>_button]:rounded-sm [&>_button]:[display:flex] [&>_button]:[gap:5px] [&>_button]:[min-height:27px] [&>_button]:[padding:0_8px] [align-items:center] [border-bottom:1px_solid_var(--border)] [display:flex] [gap:9px] [min-height:66px] [padding:8px_11px] [&>_div]:[flex:1] [&>_div]:[min-width:0] [&_small]:[color:var(--disabled-foreground)] [&_small]:[display:block] [&_small]:[margin-top:2px] [&_small]:[overflow:hidden] [&_small]:[text-overflow:ellipsis] [&_small]:[white-space:nowrap]",
  managementToolbar:
    "managementToolbar [&>_span]:[flex:1] [align-items:center] [background:var(--muted)] [border-bottom:1px_solid_var(--border)] [display:flex] [gap:5px] [height:38px] [padding:0_11px] [&>_button]:[align-items:center] [&>_button]:[background:var(--card)] [&>_button]:[border:1px_solid_var(--border)] [&>_button]:rounded-sm [&>_button]:[display:flex] [&>_button]:[gap:5px] [&>_button]:[min-height:27px] [&>_button]:[padding:0_8px] [background:var(--card)]",
  mergeOptions:
    "mergeOptions [align-items:center] [border-top:1px_solid_var(--border)] [display:flex] [gap:10px] [padding:10px_11px] [&_label]:[align-items:center] [&_label]:[color:var(--muted-foreground)] [&_label]:[display:inline-flex] [&_label]:[gap:4px] [&>_span]:[flex:1]",
  mergedBranches:
    "mergedBranches [border-top:1px_solid_var(--border)] [display:flex] [flex-direction:column] [gap:6px] [padding:11px] [&>_span]:[align-items:center] [&>_span]:[display:flex] [&>_span]:[gap:8px] [&_code]:[flex:1]",
  multiSelected: "multiSelected [background:color-mix(in_oklch,_var(--accent)_62%,_transparent)]",
  muted: "muted [color:var(--disabled-foreground)] [font-size:10px]",
  notificationToolWindow:
    "notificationToolWindow [background:var(--card)] [border:1px_solid_var(--border)] rounded-lg [bottom:18px] [box-shadow:var(--shadow-lg)] [display:grid] [grid-template-rows:30px_minmax(0,_1fr)] [position:fixed] [right:30px] [top:56px] [width:340px] [z-index:35] [&>_header]:[align-items:center] [&>_header]:[background:var(--secondary)] [&>_header]:[border-bottom:1px_solid_var(--border)] [&>_header]:[display:flex] [&>_header]:[gap:5px] [&>_header]:[padding:0_5px_0_8px] [&>_header>_strong]:[flex:1] [&>_header>_span]:[color:var(--disabled-foreground)] [&>_header>_button]:[align-items:center] [&>_header>_button]:[background:transparent] [&>_header>_button]:[display:flex] [&>_header>_button]:[height:24px] [&>_header>_button]:[justify-content:center] [&>_header>_button]:[width:24px] [&>_div]:[min-height:0] [&>_div]:[overflow:auto] [&>_div>_p]:[color:var(--muted-foreground)] [&>_div>_p]:[padding:24px] [&>_div>_p]:[text-align:center] [&_article]:[align-items:start] [&_article]:[border-bottom:1px_solid_var(--border)] [&_article]:[display:grid] [&_article]:[gap:7px] [&_article]:[grid-template-columns:18px_minmax(0,_1fr)_auto] [&_article]:[padding:8px] [&_article>_span]:[display:grid] [&_article_strong]:[font-size:11px] [&_article_small]:[color:var(--muted-foreground)] [&_article_small]:[line-height:1.35] [&_article_time]:[color:var(--disabled-foreground)] [&_article_time]:[font-size:9px]",
  notificationBalloon:
    "notificationBalloon [align-items:start] [background:var(--popover)] [border:1px_solid_var(--input)] rounded-lg [bottom:32px] [box-shadow:var(--shadow-lg)] [display:grid] [gap:8px] [grid-template-columns:17px_minmax(0,_1fr)_18px] [padding:10px_10px_9px] [position:fixed] [right:31px] [width:320px] [z-index:75] [&>_svg]:[color:var(--warning)] [&>_div]:[min-width:0] [&_strong]:[display:block] [&_p]:[color:var(--muted-foreground)] [&_p]:[line-height:1.35] [&_p]:[margin:3px_0_0] [&_p]:[max-height:34px] [&_p]:[overflow:hidden] [&_footer]:[display:flex] [&_footer]:[gap:12px] [&_footer]:[margin-top:7px] [&_footer_button]:[background:transparent] [&_footer_button]:[color:var(--primary)] [&_footer_button]:[font-size:11px] [&_footer_button]:[padding:0] [&>_button]:[align-items:center] [&>_button]:[background:transparent] [&>_button]:[color:var(--disabled-foreground)] [&>_button]:[display:flex] [&>_button]:[height:18px] [&>_button]:[justify-content:center] [&>_button]:[padding:0] [&>_button]:[width:18px]",
  paneTitle:
    "paneTitle [align-items:center] [border-bottom:1px_solid_var(--border)] [display:flex] [font-weight:650] [padding:0_6px_0_10px] [&_span]:[flex:1]",
  refActionBar:
    "refActionBar [align-items:end] [border-bottom:1px_solid_var(--border)] [display:flex] [gap:8px] [padding:9px_11px] [&>_label]:[color:var(--muted-foreground)] [&>_label]:[display:flex] [&>_label]:[flex:1] [&>_label]:[flex-direction:column] [&>_label]:[font-size:11px] [&>_label]:[gap:4px] [&>_label:nth-child(2)]:[flex:0_0_130px] max-[1120px]:[align-items:stretch] max-[1120px]:[flex-wrap:wrap]",
  refForms:
    "refForms [&_form]:[align-items:end] [&_form]:[border-bottom:1px_solid_var(--border)] [&_form]:[display:flex] [&_form]:[gap:8px] [&_form]:[padding:9px_11px] [display:grid] [gap:10px] [grid-template-columns:repeat(2,_minmax(260px,_1fr))] [padding:11px] [&_form]:[align-items:stretch] [&_form]:[background:var(--secondary)] [&_form]:[border:1px_solid_var(--border)] [&_form]:rounded-lg [&_form]:[flex-direction:column] [&_form]:[padding:11px] [&_form_strong]:[min-height:29px] max-[1120px]:[grid-template-columns:1fr]",
  refIndent: "refIndent [width:15px]",
  refManagement:
    "refManagement [height:100%] [overflow:auto] [&_input]:[background:var(--secondary)] [&_input]:[border:1px_solid_var(--border)] [&_input]:[min-height:29px] [&_input]:[padding:0_9px] [&_select]:[background:var(--secondary)] [&_select]:[border:1px_solid_var(--border)] [&_select]:[min-height:29px] [&_select]:[padding:0_9px] [&_button]:[background:var(--secondary)] [&_button]:[border:1px_solid_var(--border)] [&_button]:[min-height:29px] [&_button]:[padding:0_9px]",
  refRow:
    "refRow [align-items:center] [background:transparent] [display:flex] [gap:5px] [height:27px] [padding:0_8px] [text-align:left] [width:100%] [&:hover]:[background:var(--muted)] [&.selected]:[background:var(--accent)] [&.selected]:[color:var(--foreground)]",
  repairIdeDialog:
    "repairIdeDialog [display:grid] [grid-template-rows:auto_minmax(0,_1fr)_auto] [min-height:260px] [&>_main]:[display:flex] [&>_main]:[flex-direction:column] [&>_main]:[gap:10px] [&>_main]:[padding:18px_20px] [&>_main_h3]:[font-size:14px] [&>_main_h3]:[margin:0] [&>_main_p]:[color:var(--muted-foreground)] [&>_main_p]:[line-height:1.5] [&>_main_p]:[margin:0] [&>_main_p[role=alert]]:[color:var(--destructive)] [&>_footer]:[border-top:1px_solid_var(--border)] [&>_footer]:[display:flex] [&>_footer]:[gap:8px] [&>_footer]:[justify-content:flex-end] [&>_footer]:[padding:10px_12px]",
  repositorySettings: "repositorySettings [height:100%] [overflow:auto]",
  reviewAll: "reviewAll [min-height:0] [overflow:auto]",
  reviewAllRow:
    "reviewAllRow [border-bottom:1px_solid_var(--border)] [min-height:340px] [&>_header]:[align-items:center] [&>_header]:[background:var(--secondary)] [&>_header]:[border-bottom:1px_solid_var(--border)] [&>_header]:[display:flex] [&>_header]:[gap:7px] [&>_header]:[height:32px] [&>_header]:[padding:0_9px] [&>_header]:[position:sticky] [&>_header]:[top:0] [&>_header_>_span:nth-last-child(2)]:[flex:1] [&>_header_small]:[color:var(--disabled-foreground)] [&_pre]:[font-family:var(--font-family-code)] [&_pre]:[font-size:11px] [&_pre]:[line-height:1.5] [&_pre]:[margin:0] [&_pre]:[max-height:480px] [&_pre]:[overflow:auto] [&_pre]:[padding:10px]",
  revisionComparison:
    "revisionComparison [border-left:1px_solid_var(--border)] [display:grid] [grid-template-rows:36px_minmax(0,_1fr)] [min-height:0] [min-width:0] [position:relative] [&>_.verticalResizeHandle]:[left:-4px] [&>_.verticalResizeHandle]:[right:auto] [&>_header]:[align-items:center] [&>_header]:[border-bottom:1px_solid_var(--border)] [&>_header]:[display:flex] [&>_header]:[gap:7px] [&>_header]:[padding:0_9px] [&>_header_strong]:[margin-right:auto] [&>_header_code]:[color:var(--muted-foreground)] [&>_header_code]:[font-size:11px] [&>_[data-revision-content]]:[display:grid] [&>_[data-revision-content]]:[grid-template-columns:minmax(155px,_195px)_minmax(0,_1fr)] [&>_[data-revision-content]]:[min-height:0] [&_nav]:[border-right:1px_solid_var(--border)] [&_nav]:[min-height:0] [&_nav]:[overflow:auto] [&_nav]:[padding:4px] [&_nav_button]:[align-items:center] [&_nav_button]:[background:transparent] [&_nav_button]:[display:flex] [&_nav_button]:[gap:6px] [&_nav_button]:[min-height:28px] [&_nav_button]:[padding:3px_6px] [&_nav_button]:[text-align:left] [&_nav_button]:[width:100%] [&_nav_button.selected]:[background:var(--accent)] [&_nav_button[aria-current=true]]:[background:var(--accent)]",
  revisionFileList:
    "revisionFileList [border-bottom:1px_solid_var(--border)] [min-height:0] [overflow:auto] [padding:4px] [&>_button]:[align-items:center] [&>_button]:[background:transparent] [&>_button]:[display:flex] [&>_button]:[gap:5px] [&>_button]:[min-height:28px] [&>_button]:[padding:3px_6px] [&>_button]:[text-align:left] [&>_button]:[width:100%] [&>_button.selected]:[background:var(--accent)] [&>_button[aria-current=true]]:[background:var(--accent)] [&>_button_small]:[color:var(--disabled-foreground)] [&>_button_small]:[flex:none] [&>_button_small]:[font-size:9px]",
  revisionSummary:
    "revisionSummary [display:grid] [grid-template-rows:minmax(0,_2fr)_minmax(150px,_1fr)] [min-height:0] [min-width:0] [position:relative]",
  revisionCommitDetails:
    "revisionCommitDetails [border-top:1px_solid_var(--border)] [display:flex] [flex-direction:column] [gap:5px] [min-height:0] [overflow:auto] [padding:7px_8px] [&>_header]:[align-items:center] [&>_header]:[display:flex] [&>_header]:[gap:2px] [&>_header_strong]:[flex:1] [&>_header_button]:[background:transparent] [&>_header_button]:[height:22px] [&>_header_button]:[width:22px] [&>_strong]:[overflow-wrap:anywhere] [&>_span]:[color:var(--muted-foreground)] [&>_small]:[color:var(--disabled-foreground)] [&>_code]:[color:var(--disabled-foreground)] [&>_code]:[font-size:10px] [&>_code]:[overflow-wrap:anywhere] [&>_select]:[background:var(--secondary)] [&>_select]:[border:1px_solid_var(--border)] [&>_select]:[height:25px] [&>_select]:[width:100%] [&>_footer]:[display:flex] [&>_footer]:[flex-wrap:wrap] [&>_footer]:[gap:4px] [&>_footer_button]:[background:var(--secondary)] [&>_footer_button]:[border:1px_solid_var(--border)] [&>_footer_button]:[height:25px] [&>_footer_button]:[padding:0_6px]",
  rotated: "rotated [transform:rotate(90deg)]",
  selected: "selected [background:var(--accent)] [color:var(--foreground)]",
  selectedCommit: "selectedCommit [background:var(--accent)]!",
  settingRow:
    "settingRow [align-items:center] [border-top:1px_solid_var(--border)] [display:flex] [gap:8px] [min-height:48px] [padding:7px_11px] [&>_div]:[display:flex] [&>_div]:[flex:1] [&>_div]:[flex-direction:column] [&>_div]:[min-width:0] [&_small]:[color:var(--disabled-foreground)] [&_small]:[overflow:hidden] [&_small]:[text-overflow:ellipsis] [&_small]:[white-space:nowrap]",
  settingsSection:
    "settingsSection [border-bottom:1px_solid_var(--border)] [&>_header]:[align-items:center] [&>_header]:[background:var(--muted)] [&>_header]:[border-bottom:1px_solid_var(--border)] [&>_header]:[display:flex] [&>_header]:[gap:8px] [&>_header]:[min-height:37px] [&>_header]:[padding:6px_11px] [&>_header_>_span]:[flex:1] [&_button]:[background:var(--secondary)] [&_button]:[border:1px_solid_var(--border)] [&_button]:[min-height:28px] [&_button]:[padding:0_8px] [&_input]:[background:var(--secondary)] [&_input]:[border:1px_solid_var(--border)] [&_input]:[min-height:28px] [&_input]:[padding:0_8px] [&_select]:[background:var(--secondary)] [&_select]:[border:1px_solid_var(--border)] [&_select]:[min-height:28px] [&_select]:[padding:0_8px]",
  settingsDialog:
    "settingsDialog [display:grid] [grid-template-columns:230px_minmax(0,_1fr)] [grid-template-rows:auto_minmax(0,_1fr)_auto] [height:min(680px,_calc(100vh_-_70px))] [min-height:0] [&>_[data-slot=dialog-header]]:[grid-column:1/-1] [&>_aside]:[background:var(--muted)] [&>_aside]:[border-right:1px_solid_var(--border)] [&>_aside]:[display:flex] [&>_aside]:[flex-direction:column] [&>_aside]:[gap:2px] [&>_aside]:[padding:7px] [&>_aside_button]:[align-items:center] [&>_aside_button]:[background:transparent] [&>_aside_button]:[display:flex] [&>_aside_button]:[gap:8px] [&>_aside_button]:[height:31px] [&>_aside_button]:[padding:0_8px] [&>_aside_button]:[text-align:left] [&>_main]:[min-height:0] [&>_main]:[overflow:auto] [&>_footer]:[border-top:1px_solid_var(--border)] [&>_footer]:[display:flex] [&>_footer]:[grid-column:1/-1] [&>_footer]:[justify-content:flex-end] [&>_footer]:[padding:8px_12px]",
  settingsPage:
    "settingsPage [display:flex] [flex-direction:column] [gap:14px] [padding:18px_20px] [&>_h2]:[font-size:16px] [&>_h2]:[margin:0] [&>_p]:[color:var(--muted-foreground)] [&>_p]:[line-height:1.5] [&>_p]:[margin:0]",
  keymapTable:
    "keymapTable [border:1px_solid_var(--border)] rounded-lg [min-height:0] [overflow:auto] [&>_div]:[align-items:center] [&>_div]:[border-top:1px_solid_var(--border)] [&>_div]:[display:grid] [&>_div]:[gap:8px] [&>_div]:[grid-template-columns:minmax(0,_1fr)_130px_50px] [&>_div]:[min-height:39px] [&>_div]:[padding:4px_9px] [&>_div:first-child]:[border-top:0] [&>_div_span]:[display:grid] [&>_div_span]:[min-width:0] [&>_div_strong]:[overflow:hidden] [&>_div_strong]:[text-overflow:ellipsis] [&>_div_strong]:[white-space:nowrap] [&>_div_small]:[color:var(--muted-foreground)] [&>_div_small]:[font-size:9px] [&>_div_button]:[background:var(--muted)] [&>_div_button]:[border:1px_solid_var(--border)] [&>_div_button]:rounded-sm [&>_div_button]:[height:26px] [&>_div_button]:[padding:0_7px] [&>_div_button:first-of-type]:[font-family:ui-monospace,_SFMono-Regular,_Menlo,_monospace]",
  invalidateCachesDialog:
    "invalidateCachesDialog [display:grid] [grid-template-rows:auto_minmax(0,_1fr)_auto] [min-height:220px] [&>_main]:[display:flex] [&>_main]:[flex-direction:column] [&>_main]:[gap:10px] [&>_main]:[padding:18px_20px] [&>_main_p]:[color:var(--muted-foreground)] [&>_main_p]:[line-height:1.5] [&>_main_p]:[margin:0] [&>_footer]:[border-top:1px_solid_var(--border)] [&>_footer]:[display:flex] [&>_footer]:[gap:8px] [&>_footer]:[justify-content:flex-end] [&>_footer]:[padding:10px_12px]",
  runConfigurationTemplatesDialog:
    "runConfigurationTemplatesDialog [display:grid] [grid-template-columns:220px_minmax(0,_1fr)] [grid-template-rows:auto_minmax(0,_1fr)_auto] [height:min(590px,_calc(100vh_-_70px))] [min-height:0] [&>_[data-slot=dialog-header]]:[grid-column:1/-1] [&>_aside]:[background:var(--muted)] [&>_aside]:[border-right:1px_solid_var(--border)] [&>_aside]:[display:flex] [&>_aside]:[flex-direction:column] [&>_aside]:[gap:2px] [&>_aside]:[padding:10px_7px] [&>_aside_>_strong]:[color:var(--muted-foreground)] [&>_aside_>_strong]:[font-size:10px] [&>_aside_>_strong]:[padding:2px_8px_7px] [&>_aside_button]:[align-items:center] [&>_aside_button]:[background:transparent] [&>_aside_button]:[display:flex] [&>_aside_button]:[gap:8px] [&>_aside_button]:[height:31px] [&>_aside_button]:[padding:0_8px] [&>_aside_button]:[text-align:left] [&>_main]:[display:flex] [&>_main]:[flex-direction:column] [&>_main]:[gap:15px] [&>_main]:[min-height:0] [&>_main]:[overflow:auto] [&>_main]:[padding:18px_20px] [&>_main_h2]:[font-size:16px] [&>_main_h2]:[margin:0] [&>_main_p]:[color:var(--muted-foreground)] [&>_main_p]:[margin:0] [&>_footer]:[border-top:1px_solid_var(--border)] [&>_footer]:[display:flex] [&>_footer]:[grid-column:1/-1] [&>_footer]:[justify-content:flex-end] [&>_footer]:[padding:8px_12px]",
  settingsTabs:
    "settingsTabs [align-items:center] [border-bottom:1px_solid_var(--border)] [display:flex] [gap:4px] [padding:8px_11px] [&>_button]:[background:transparent] [&>_button]:[min-height:29px] [&>_button]:[padding:0_10px] [&_em]:[color:var(--disabled-foreground)] [&_em]:[font-size:10px] [&_em]:[font-style:normal] [&_em]:[margin-left:4px]",
  signatureBad: "signatureBad [color:var(--destructive)]",
  signatureGood: "signatureGood [color:var(--success)]",
  scratchEditor:
    "scratchEditor [background:var(--card)] [height:100%] [min-height:0] [min-width:0] [overflow:hidden]",
  scratchFileChooserDialog:
    "scratchFileChooserDialog [display:grid] [grid-template-rows:auto_auto_minmax(0,_1fr)] [max-height:min(540px,_calc(100vh_-_90px))] [min-height:360px] [&>_[data-slot=text-input]]:[margin:10px_12px_6px] [&>_div[role=listbox]]:[min-height:0] [&>_div[role=listbox]]:[overflow:auto] [&>_div[role=listbox]]:[padding:3px_7px_9px] [&>_div[role=listbox]_button]:[align-items:center] [&>_div[role=listbox]_button]:[background:transparent] [&>_div[role=listbox]_button]:[display:grid] [&>_div[role=listbox]_button]:[gap:8px] [&>_div[role=listbox]_button]:[grid-template-columns:18px_minmax(0,_1fr)_auto] [&>_div[role=listbox]_button]:[min-height:30px] [&>_div[role=listbox]_button]:[padding:0_8px] [&>_div[role=listbox]_button]:[text-align:left] [&>_div[role=listbox]_button]:[width:100%] [&>_div[role=listbox]_button:hover]:[background:var(--muted)] [&>_div[role=listbox]_button:focus]:[background:var(--accent)] [&>_div[role=listbox]_button_small]:[color:var(--disabled-foreground)]",
  savedMacrosDialog:
    "savedMacrosDialog [display:grid] [grid-template-rows:auto_minmax(240px,_1fr)_auto] [max-height:min(560px,_calc(100vh_-_80px))] [&>_main]:[min-height:0] [&>_main]:[overflow:auto] [&>_main]:[padding:6px] [&>_footer]:[border-top:1px_solid_var(--border)] [&>_footer]:[display:flex] [&>_footer]:[justify-content:flex-end] [&>_footer]:[padding:8px_10px]",
  recentFindUsagesDialog:
    "recentFindUsagesDialog [display:grid] [grid-template-rows:auto_minmax(190px,_1fr)] [max-height:min(480px,_calc(100vh_-_90px))] [&>_[data-slot=empty-state]]:[min-height:190px] [&>_div[role=listbox]]:[min-height:0] [&>_div[role=listbox]]:[overflow:auto] [&>_div[role=listbox]]:[padding:6px]",
  vcsOperationsPopup:
    "vcsOperationsPopup [display:grid] [grid-template-rows:auto_minmax(0,_1fr)] [max-height:min(720px,_calc(100vh_-_82px))] [&>_main]:[min-height:0] [&>_main]:[overflow:auto] [&>_main]:[padding:5px] [&>_main>_section]:[padding:2px_0] [&>_main>_section+section]:[border-top:1px_solid_var(--border)] [&>_main_h3]:[color:var(--muted-foreground)] [&>_main_h3]:[font-size:10px] [&>_main_h3]:[font-weight:600] [&>_main_h3]:[margin:4px_8px_2px] [&>_main_kbd]:[color:var(--disabled-foreground)] [&>_main_kbd]:[font-family:var(--font-family-code)] [&>_main_[aria-disabled=true]]:[opacity:.48]",
  processesDialog:
    "processesDialog [display:grid] [grid-template-rows:auto_minmax(220px,_1fr)_auto] [max-height:min(580px,_calc(100vh_-_80px))] [&>_main]:[min-height:0] [&>_main]:[overflow:auto] [&>_main>_div[role=list]]:[padding:6px] [&>_main>_[data-slot=empty-state]]:[min-height:220px] [&>_footer]:[align-items:center] [&>_footer]:[border-top:1px_solid_var(--border)] [&>_footer]:[display:flex] [&>_footer]:[gap:8px] [&>_footer]:[padding:8px_10px] [&>_footer>_span]:[flex:1]",
  activityMonitorDialog:
    "activityMonitorDialog [display:grid] [grid-template-rows:auto_30px_minmax(300px,_1fr)_auto] [height:min(620px,_calc(100vh_-_80px))] [&>_header]:[align-items:center] [&>_header]:[border-bottom:1px_solid_var(--border)] [&>_header]:[color:var(--muted-foreground)] [&>_header]:[display:grid] [&>_header]:[grid-template-columns:minmax(0,_1fr)_90px_100px] [&>_header]:[padding:0_12px] [&>_header]:[font-size:11px] [&>_main]:[min-height:0] [&>_main]:[overflow:auto] [&>_main>_div[role=list]]:[padding:5px] [&>_footer]:[align-items:center] [&>_footer]:[border-top:1px_solid_var(--border)] [&>_footer]:[color:var(--muted-foreground)] [&>_footer]:[display:flex] [&>_footer]:[justify-content:space-between] [&>_footer]:[padding:8px_10px]",
  activityMonitorMetrics:
    "activityMonitorMetrics [display:grid] [font-variant-numeric:tabular-nums] [grid-template-columns:90px_100px] [text-align:right]",
  configurationFileDialog:
    "configurationFileDialog [display:grid] [grid-template-rows:auto_minmax(360px,_1fr)_auto] [max-height:min(700px,_calc(100vh_-_70px))] [&>_main]:[display:grid] [&>_main]:[gap:10px] [&>_main]:[min-height:0] [&>_main]:[padding:12px] [&>_main>_p]:[color:var(--muted-foreground)] [&>_main>_p]:[margin:0] [&>_main>_div[role=alert]]:[color:var(--destructive)] [&>_footer]:[border-top:1px_solid_var(--border)] [&>_footer]:[display:flex] [&>_footer]:[gap:8px] [&>_footer]:[justify-content:flex-end] [&>_footer]:[padding:8px_10px]",
  specialFilesDialog:
    "specialFilesDialog [display:grid] [grid-template-rows:auto_minmax(260px,_1fr)_auto] [&>_div[role=list]]:[padding:6px] [&>_footer]:[border-top:1px_solid_var(--border)] [&>_footer]:[display:flex] [&>_footer]:[justify-content:flex-end] [&>_footer]:[padding:8px_10px]",
  leftoverDirectoriesDialog:
    "leftoverDirectoriesDialog [display:grid] [grid-template-rows:auto_auto_30px_minmax(260px,_1fr)_auto] [height:min(620px,_calc(100vh_-_80px))] [&>_p]:[color:var(--muted-foreground)] [&>_p]:[margin:0] [&>_p]:[padding:11px_13px] [&>_header]:[align-items:center] [&>_header]:[border-bottom:1px_solid_var(--border)] [&>_header]:[color:var(--muted-foreground)] [&>_header]:[display:grid] [&>_header]:[font-size:11px] [&>_header]:[grid-template-columns:minmax(0,_1fr)_130px_90px] [&>_header]:[padding:0_12px_0_46px] [&>_main]:[min-height:0] [&>_main]:[overflow:auto] [&>_main>_div[role=list]]:[padding:5px] [&>_footer]:[align-items:center] [&>_footer]:[border-top:1px_solid_var(--border)] [&>_footer]:[display:flex] [&>_footer]:[gap:8px] [&>_footer]:[padding:8px_10px] [&>_footer>_span]:[color:var(--muted-foreground)] [&>_footer>_span]:[flex:1]",
  leftoverDirectoryMetrics:
    "leftoverDirectoryMetrics [align-items:center] [color:var(--muted-foreground)] [display:grid] [font-variant-numeric:tabular-nums] [grid-template-columns:130px_90px] [&>_span]:[text-align:right]",
  productHelpDialog:
    "productHelpDialog [display:grid] [grid-template-rows:auto_minmax(300px,_1fr)_auto] [&>_main]:[min-height:0] [&>_main]:[overflow:auto] [&>_main>_p]:[color:var(--muted-foreground)] [&>_main>_p]:[margin:14px_16px_8px] [&>_main>_div[role=list]]:[padding:5px_9px_12px] [&>_footer]:[border-top:1px_solid_var(--border)] [&>_footer]:[display:flex] [&>_footer]:[justify-content:flex-end] [&>_footer]:[padding:8px_10px]",
  whatsNewDialog:
    "whatsNewDialog [display:grid] [grid-template-rows:auto_minmax(300px,_1fr)_auto] [&>_main]:[min-height:0] [&>_main]:[overflow:auto] [&>_main>_p]:[color:var(--muted-foreground)] [&>_main>_p]:[margin:14px_16px_8px] [&>_main>_div[role=list]]:[padding:5px_9px_12px] [&>_footer]:[border-top:1px_solid_var(--border)] [&>_footer]:[display:flex] [&>_footer]:[justify-content:flex-end] [&>_footer]:[padding:8px_10px]",
  commandLineLauncherDialog:
    "commandLineLauncherDialog [display:grid] [grid-template-rows:auto_minmax(180px,_auto)_auto] [&>_main]:[align-content:center] [&>_main]:[display:grid] [&>_main]:[gap:10px] [&>_main]:[padding:18px] [&>_main_p]:[color:var(--muted-foreground)] [&>_main_p]:[line-height:1.5] [&>_main_p]:[margin:0] [&>_main_code]:[color:var(--foreground)] [&>_main_pre]:[background:var(--muted)] [&>_main_pre]:[border:1px_solid_var(--border)] [&>_main_pre]:rounded-md [&>_main_pre]:[font-family:var(--font-family-code)] [&>_main_pre]:[margin:0] [&>_main_pre]:[overflow:auto] [&>_main_pre]:[padding:9px_11px] [&>_footer]:[border-top:1px_solid_var(--border)] [&>_footer]:[display:flex] [&>_footer]:[justify-content:flex-end] [&>_footer]:[padding:8px_10px]",
  shareProjectDialog:
    "shareProjectDialog [display:grid] [grid-template-rows:auto_minmax(0,_1fr)_auto] [max-height:min(720px,_calc(100vh_-_70px))] [&>_main]:[display:grid] [&>_main]:[gap:12px] [&>_main]:[min-height:0] [&>_main]:[overflow:auto] [&>_main]:[padding:14px] [&>_main>_p]:[color:var(--muted-foreground)] [&>_main>_p]:[margin:0] [&>_main>_p[role=alert]]:[color:var(--destructive)] [&>_footer]:[border-top:1px_solid_var(--border)] [&>_footer]:[display:flex] [&>_footer]:[gap:8px] [&>_footer]:[justify-content:flex-end] [&>_footer]:[padding:8px_10px]",
  shareProjectAccount:
    "shareProjectAccount [align-items:end] [display:grid] [gap:8px] [grid-template-columns:minmax(0,_1fr)_auto]",
  shareProjectCoordinates:
    "shareProjectCoordinates [align-items:end] [display:grid] [gap:12px] [grid-template-columns:minmax(0,_1fr)_auto]",
  shareInitialCommitDialog:
    "shareInitialCommitDialog [display:grid] [grid-template-rows:auto_32px_minmax(220px,_1fr)_auto_auto] [height:min(640px,_calc(100vh_-_70px))] [&>_header]:[align-items:center] [&>_header]:[border-bottom:1px_solid_var(--border)] [&>_header]:[color:var(--muted-foreground)] [&>_header]:[display:flex] [&>_header]:[justify-content:space-between] [&>_header]:[padding:0_10px_0_13px] [&>_main]:[min-height:0] [&>_main]:[overflow:auto] [&>_main>_p]:[color:var(--muted-foreground)] [&>_main>_p]:[margin:18px] [&>_main>_div[role=list]]:[padding:5px_7px] [&>_[data-slot=text-area]]:[border-top:1px_solid_var(--border)] [&>_[data-slot=text-area]]:[padding:10px_12px] [&>_footer]:[border-top:1px_solid_var(--border)] [&>_footer]:[display:flex] [&>_footer]:[gap:8px] [&>_footer]:[justify-content:flex-end] [&>_footer]:[padding:8px_10px]",
  shareExistingRemotesDialog:
    "shareExistingRemotesDialog [display:grid] [grid-template-rows:auto_minmax(120px,_auto)_auto] [&>_main]:[align-items:start] [&>_main]:[display:grid] [&>_main]:[gap:12px] [&>_main]:[grid-template-columns:32px_minmax(0,_1fr)] [&>_main]:[padding:18px] [&>_main_p]:[margin:0_0_8px] [&>_main_>_section_>_div[role=list]]:[padding:0] [&>_main_>_section_>_div[role=list]_li]:[color:var(--primary)] [&>_footer]:[border-top:1px_solid_var(--border)] [&>_footer]:[display:flex] [&>_footer]:[gap:8px] [&>_footer]:[justify-content:flex-end] [&>_footer]:[padding:8px_10px]",
  toolWindowLayoutsDialog:
    "toolWindowLayoutsDialog [display:grid] [grid-template-rows:auto_minmax(180px,_1fr)] [max-height:min(520px,_calc(100vh_-_80px))] [&>_div[role=listbox]]:[min-height:0] [&>_div[role=listbox]]:[overflow:auto] [&>_div[role=listbox]]:[padding:6px]",
  codeAnalysisScopeDialog:
    "codeAnalysisScopeDialog [display:grid] [grid-template-rows:auto_minmax(0,_1fr)_auto] [&>_main]:[display:grid] [&>_main]:[gap:16px] [&>_main]:[padding:18px_20px] [&>_main_p]:[color:var(--destructive)] [&>_main_p]:[margin:0] [&>_footer]:[border-top:1px_solid_var(--border)] [&>_footer]:[display:flex] [&>_footer]:[gap:8px] [&>_footer]:[justify-content:flex-end] [&>_footer]:[padding:9px_11px]",
  runInspectionDialog:
    "runInspectionDialog [display:grid] [grid-template-rows:auto_auto_minmax(260px,_1fr)_auto] [height:min(580px,_calc(100vh_-_80px))] [&>_[data-slot=text-input]]:[margin:10px_12px_5px] [&>_div[role=listbox]]:[min-height:0] [&>_div[role=listbox]]:[overflow:auto] [&>_div[role=listbox]]:[padding:5px_7px] [&>_footer]:[border-top:1px_solid_var(--border)] [&>_footer]:[display:flex] [&>_footer]:[justify-content:flex-end] [&>_footer]:[padding:8px_10px]",
  inspectionResultsDialog:
    "inspectionResultsDialog [display:grid] [grid-template-rows:auto_32px_minmax(300px,_1fr)_auto] [height:min(680px,_calc(100vh_-_80px))] [&>_header]:[align-items:center] [&>_header]:[border-bottom:1px_solid_var(--border)] [&>_header]:[display:flex] [&>_header]:[gap:7px] [&>_header]:[padding:0_10px] [&>_header_span]:[color:var(--muted-foreground)] [&>_div[role=listbox]]:[min-height:0] [&>_div[role=listbox]]:[overflow:auto] [&>_div[role=listbox]]:[padding:5px_7px] [&>_footer]:[border-top:1px_solid_var(--border)] [&>_footer]:[display:flex] [&>_footer]:[justify-content:flex-end] [&>_footer]:[padding:8px_10px]",
  stackTraceDialog:
    "stackTraceDialog [display:grid] [grid-template-rows:auto_minmax(0,_1fr)_auto] [height:min(680px,_calc(100vh_-_80px))] [&>_main]:[display:grid] [&>_main]:[gap:10px] [&>_main]:[grid-template-rows:auto_minmax(0,_1fr)] [&>_main]:[min-height:0] [&>_main]:[padding:12px] [&>_main_>_div[role=listbox]]:[min-height:0] [&>_main_>_div[role=listbox]]:[overflow:auto] [&>_footer]:[border-top:1px_solid_var(--border)] [&>_footer]:[display:flex] [&>_footer]:[justify-content:flex-end] [&>_footer]:[padding:8px_10px]",
  srOnly:
    "srOnly [clip:rect(0_0_0_0)] [clip-path:inset(50%)] [height:1px] [overflow:hidden] [position:absolute] [left:0] [top:0] [white-space:nowrap] [width:1px]",
  standaloneDiff:
    "standaloneDiff [background:var(--card)] [display:grid] [grid-template-rows:38px_minmax(0,_1fr)] [inset:70px_0_23px] [position:fixed] [z-index:44] [&>_header]:[align-items:center] [&>_header]:[border-bottom:1px_solid_var(--border)] [&>_header]:[display:flex] [&>_header]:[padding:0_9px] [&>_header_span]:[flex:1]",
  stashEntry:
    "stashEntry [border-bottom:1px_solid_var(--border)] [&.collectionRow]:[border-bottom:0]",
  stashFiles:
    "stashFiles [background:var(--muted)] [display:grid] [gap:3px] [padding:6px_14px_8px_48px] [&_span]:[color:var(--muted-foreground)] [&_span]:[font-family:var(--font-family-code)] [&_strong]:[color:var(--primary)] [&_strong]:[display:inline-block] [&_strong]:[margin-right:8px] [&_strong]:[width:12px]",
  statusAdded:
    "statusAdded [background:color-mix(in_oklch,_var(--success)_16%,_transparent)] [color:var(--success)]",
  statusConflict:
    "statusConflict [background:color-mix(in_oklch,_var(--destructive)_16%,_transparent)] [color:var(--destructive)]",
  statusDeleted:
    "statusDeleted [background:color-mix(in_oklch,_var(--destructive)_16%,_transparent)] [color:var(--destructive)]",
  statusModified:
    "statusModified [background:color-mix(in_oklch,_var(--primary)_16%,_transparent)] [color:var(--primary)]",
  statusRenamed:
    "statusRenamed [background:color-mix(in_oklch,_var(--primary)_16%,_transparent)] [color:var(--primary)]",
  statusUnknown: "statusUnknown [background:var(--muted)] [color:var(--muted-foreground)]",
  statusbar:
    "statusbar [align-items:center] [background:var(--card)] [border-top:1px_solid_var(--border)] [color:var(--muted-foreground)] [display:flex] [font-size:9px] [gap:5px] [padding:0_5px_0_8px] [&>_nav]:[flex:1] [&>_nav]:[min-width:0] [&>_span]:[align-items:center] [&>_span]:[display:flex] [&>_span]:[gap:4px]",
  statusbarSpacer: "statusbarSpacer [flex:1] [min-width:0]",
  statusbarWidgets: "statusbarWidgets [align-self:stretch] [display:flex] [gap:0]!",
  topNavigationBar:
    "topNavigationBar [align-items:center] [background:var(--card)] [border-bottom:1px_solid_var(--border)] [display:flex] [height:26px] [left:31px] [padding:0_8px] [position:absolute] [right:30px] [top:30px] [z-index:9]",
  submoduleDiff:
    "submoduleDiff [display:grid] [align-content:center] [justify-items:center] [gap:10px] [min-height:100%] [padding:28px] [color:var(--muted-foreground)] [text-align:center] [&>_strong]:[color:var(--foreground)] [&>_div]:[display:grid] [&>_div]:[grid-template-columns:minmax(0,_1fr)_auto_minmax(0,_1fr)] [&>_div]:[align-items:center] [&>_div]:[gap:12px] [&>_div]:[width:min(680px,_100%)] [&_section]:[display:grid] [&_section]:[gap:6px] [&_section]:[min-width:0] [&_section]:[padding:12px] [&_section]:[border:1px_solid_var(--border)] [&_section]:rounded-lg [&_section]:[background:var(--secondary)] [&_section]:[text-align:left] [&_code]:[overflow:hidden] [&_code]:[color:var(--foreground)] [&_code]:[font-size:11px] [&_code]:[text-overflow:ellipsis]",
  terminalStatus: "terminalStatus [display:none]",
  terminalSurface:
    "terminalSurface [background:var(--terminal-background)] [min-height:0] [overflow:hidden] [&>_div:not([data-slot=empty])]:[height:100%]",
  terminalTab:
    "terminalTab [align-items:center] [background:transparent] [color:var(--muted-foreground)] [display:flex] [gap:6px] [min-width:0] [padding:0_4px_0_9px] [&>_span:last-child]:[overflow:hidden] [&>_span:last-child]:[text-overflow:ellipsis] [&>_span:last-child]:[white-space:nowrap]",
  terminalTabItem:
    "terminalTabItem [align-items:center] [background:var(--accent)] rounded-sm [display:flex] [margin:3px_0] [min-width:0]",
  terminalTabList:
    "terminalTabList [align-items:stretch] [display:flex] [flex:none] [min-width:0] [overflow-x:auto]",
  terminalTabs:
    "terminalTabs [align-items:stretch] [background:var(--card)] [border-bottom:1px_solid_var(--border)] [display:flex] [min-width:0] [&_.activeTerminalTab]:[background:var(--accent)] [&_.activeTerminalTab]:[color:var(--foreground)] [&>_.terminalToolbar:last-child]:[margin-left:auto]",
  terminalToolTitle:
    "terminalToolTitle [align-items:center] [display:flex] [font-size:12px] [padding:0_9px]",
  terminalToolbar: "terminalToolbar [align-items:stretch] [display:flex]",
  terminalTool:
    "terminalTool [display:grid] [grid-template-rows:30px_minmax(0,_1fr)] [height:100%] [min-height:0]",
  titlebar:
    "titlebar [align-items:center] [background:var(--card)] [border-bottom:1px_solid_var(--border)] [display:flex] [gap:2px] [padding-right:5px] [user-select:none] [&>_button]:[align-items:center] [&>_button]:[background:transparent] [&>_button]:[color:var(--muted-foreground)] [&>_button]:[display:flex] [&>_button]:[height:26px] [&>_button]:[justify-content:center] [&>_button:hover]:[background:var(--muted)] [&>_button:hover]:[color:var(--foreground)]",
  toast:
    "toast [align-items:center] [background:var(--inverse)] rounded-lg [bottom:36px] [box-shadow:var(--shadow-lg)] [color:var(--inverse-foreground)] [display:flex] [gap:7px] [left:50%] [padding:9px_13px] [position:fixed] [transform:translateX(-50%)] [z-index:80]",
  toolContent: "toolContent [min-height:0] [overflow:hidden]",
  toolTabs:
    "toolTabs [align-items:stretch] [background:var(--secondary)] [display:flex] [&_button]:[align-items:center] [&_button]:[background:transparent] [&_button]:[border-right:1px_solid_var(--border)] [&_button]:[color:var(--muted-foreground)] [&_button]:[display:flex] [&_button]:[gap:6px] [&_button]:[padding:0_12px] [&_button:hover]:[background:var(--muted)] [&_button:hover]:[color:var(--foreground)] [&_.activeToolTab]:[box-shadow:inset_0_-2px_var(--primary)] [&_.activeToolTab]:[color:var(--foreground)] [&_.activeToolTab]:[font-weight:600] [&_button_em]:[align-items:center] [&_button_em]:[background:var(--muted)] [&_button_em]:rounded-lg [&_button_em]:[display:flex] [&_button_em]:[font-size:9px] [&_button_em]:[font-style:normal] [&_button_em]:[height:14px] [&_button_em]:[justify-content:center] [&_button_em]:[min-width:14px] [&>_span]:[flex:1] [background:var(--card)]",
  trafficSpace: "trafficSpace [flex:0_0_74px] max-[1050px]:[flex-basis:64px]",
  projectMark:
    "projectMark [align-items:center] [background:var(--primary)] rounded-xs [color:var(--primary-foreground)] [display:inline-flex] [font-size:9px] [font-weight:700] [height:16px] [justify-content:center] [width:16px]",
  presentationAssistant:
    "presentationAssistant [background:var(--popover)] [border:1px_solid_var(--input)] rounded-lg [bottom:42px] [box-shadow:var(--shadow-lg)] [color:var(--foreground)] [font-size:14px] [font-weight:600] [left:50%] [padding:10px_16px] [position:fixed] [transform:translateX(-50%)] [z-index:180]",
  mainToolbarPopupAnchor:
    "mainToolbarPopupAnchor [align-self:stretch] [display:flex] [position:relative]",
  mainToolbarDragRegion: "mainToolbarDragRegion [flex:1] [height:100%]",
  editorTabs: "editorTabs [align-items:center] [align-self:stretch] [display:flex]",
  editorSurface:
    "editorSurface [height:100%] [min-height:0] [min-width:0] [&[hidden]]:[display:none]",
  editorToolbarSpacer: "editorToolbarSpacer [flex:1]",
  toolStripe:
    "toolStripe [background:var(--card)] [border-right:1px_solid_var(--border)] [display:flex] [flex-direction:column] [justify-content:space-between] [min-height:0] [padding:3px_0] [&>_div]:[display:flex] [&>_div]:[flex-direction:column] [&_button_em]:[align-items:center] [&_button_em]:[background:var(--primary)] [&_button_em]:rounded-lg [&_button_em]:[color:var(--primary-foreground)] [&_button_em]:[display:flex] [&_button_em]:[font-size:8px] [&_button_em]:[font-style:normal] [&_button_em]:[height:13px] [&_button_em]:[justify-content:center] [&_button_em]:[min-width:13px] [&_button_em]:[position:absolute] [&_button_em]:[right:1px] [&_button_em]:[top:1px]",
  rightToolStripe:
    "rightToolStripe [background:var(--card)] [border-left:1px_solid_var(--border)] [min-height:0] [padding:3px_0] [&_button_em]:[background:var(--primary)] [&_button_em]:rounded-full [&_button_em]:[display:block] [&_button_em]:[height:7px] [&_button_em]:[position:absolute] [&_button_em]:[right:3px] [&_button_em]:[top:2px] [&_button_em]:[width:7px]",
  treeGroup:
    "treeGroup [align-items:center] [background:transparent] [display:flex] [gap:5px] [height:27px] [padding:0_8px] [text-align:left] [width:100%] [color:var(--muted-foreground)] [font-size:11px] [font-weight:650] [text-transform:uppercase] [&_small]:[color:var(--disabled-foreground)] [&_small]:[font-weight:400] [&_small]:[margin-left:auto] [&_svg:first-child]:[transform:rotate(0deg)] [&_svg:first-child]:[transition:transform_0.12s] [&.rotated]:[transform:rotate(90deg)] [&:hover]:[background:var(--muted)]",
  treeSearch:
    "treeSearch [align-items:center] [background:var(--secondary)] [border:1px_solid_var(--border)] rounded-sm [display:flex] [gap:5px] [margin:6px_7px] [padding:0_7px] [&:focus-within]:[border-color:var(--primary)] [&:focus-within]:[box-shadow:0_0_0_1px_color-mix(in_oklch,_var(--primary)_20%,_transparent)] [&_input]:[background:transparent] [&_input]:[border:0] [&_input]:[height:24px] [&_input]:[min-width:0] [&_input]:[outline:0] [&_input]:[width:100%]",
  treeVirtualRow: "treeVirtualRow [height:27px] [left:0] [position:absolute] [right:0] [top:0]",
  unsupportedDiff:
    "unsupportedDiff [align-items:center] [color:var(--muted-foreground)] [display:flex] [flex-direction:column] [height:100%] [justify-content:center] [text-align:center] [&_strong]:[color:var(--foreground)] [&_strong]:[margin-top:9px] [&_p]:[max-width:380px] [&_button]:[align-items:center] [&_button]:[background:var(--muted)] [&_button]:[border:1px_solid_var(--border)] [&_button]:rounded-sm [&_button]:[display:inline-flex] [&_button]:[gap:6px] [&_button]:[height:29px] [&_button]:[padding:0_10px]",
  verticalResizeHandle:
    'verticalResizeHandle [bottom:0] [cursor:col-resize] [position:absolute] [right:-4px] [top:0] [width:7px] [z-index:12] [&::after]:[background:transparent] [&::after]:[content:\\"\\"] [&::after]:[inset:0_3px] [&::after]:[position:absolute] [&::after]:[transition:background_100ms_ease-out] [&:hover::after]:[background:var(--primary)] [&:focus-visible::after]:[background:var(--primary)] max-[1120px]:[display:none]',
  virtualTree: "virtualTree [min-height:0] [overflow:auto]",
  workspace: "workspace [grid-row:2_/_4] [min-height:0] [position:relative]",
  workbench:
    "workbench [display:grid] [grid-template-columns:30px_minmax(0,_1fr)_30px] [height:100%] [min-height:0] [min-width:0]",
  workbenchSurface:
    "workbenchSurface [background:var(--background)] [display:grid] [grid-template-rows:minmax(0,_1fr)_auto] [min-height:0] [min-width:0]",
  workbenchContent:
    "workbenchContent [display:grid] [gap:6px] [grid-template-columns:minmax(0,_1fr)] [min-height:0] [min-width:0]",
  maximizedSideTool:
    "maximizedSideTool [grid-template-columns:minmax(0,_1fr)] [&>_[data-workspace-main]]:[display:none]",
  maximizedBottomTool:
    "maximizedBottomTool [grid-template-rows:minmax(0,_1fr)] [&>_.workbenchContent]:[display:none] [&>_[data-tool-window-position=bottom]]:[height:100%!important]",
  welcomeBrand:
    "welcomeBrand [align-items:center] [display:flex] [gap:10px] [height:64px] [padding:12px_16px_8px] [&>_span:last-child]:[display:flex] [&>_span:last-child]:[flex-direction:column] [&_strong]:[font-size:13px] [&_strong]:[font-weight:500] [&_small]:[color:var(--muted-foreground)] [&_small]:[font-size:10px]",
  welcomeBrandMark:
    "welcomeBrandMark [align-items:center] [background:var(--primary)] rounded-sm [color:var(--primary-foreground)] [display:flex] [height:31px] [justify-content:center] [width:31px]",
  welcomeNavigation:
    "welcomeNavigation [display:flex] [flex-direction:column] [gap:1px] [padding:20px_12px] [&>_button]:[background:transparent] [&>_button]:[height:32px] [&>_button]:[padding:0_23px] [&>_button]:[text-align:left] [&>_button:hover]:[background:color-mix(in_oklch,_var(--foreground)_5%,_transparent)] [&>_button[aria-current=page]]:[background:var(--sidebar-accent)] [&>_button:focus-visible]:[outline:2px_solid_var(--primary)] [&>_button:focus-visible]:[outline-offset:-2px]",
  welcomeCustomize:
    "welcomeCustomize [background:var(--card)] [min-height:0] [overflow:auto] [padding:30px_30px_18px]",
  welcomeProjectActions:
    "welcomeProjectActions [display:flex] [gap:56px] [justify-content:center] [&>_button]:[align-items:center] [&>_button]:[background:transparent] [&>_button]:[display:flex] [&>_button]:[flex-direction:column] [&>_button]:[font-size:13px] [&>_button]:[gap:12px] [&>_button]:[min-width:64px] [&>_button]:[padding:0] [&>_button>_span]:[align-items:center] [&>_button>_span]:[background:var(--muted)] [&>_button>_span]:rounded-sm [&>_button>_span]:[color:var(--primary)] [&>_button>_span]:[display:flex] [&>_button>_span]:[height:54px] [&>_button>_span]:[justify-content:center] [&>_button>_span]:[width:54px] [&>_button:hover>_span]:[background:var(--accent)]",
  welcomeProjects:
    "welcomeProjects [display:grid] [grid-template-rows:auto_auto_minmax(0,_1fr)] [min-height:0] [padding:104px_30px_34px] [position:relative] [&>_header]:[text-align:center] [&>_header_h1]:[font-size:27px] [&>_header_h1]:[line-height:1.2] [&>_header_h1]:[margin:0_0_20px] [&>_header_p]:[color:var(--muted-foreground)] [&>_header_p]:[font-size:13px] [&>_header_p]:[margin:0_0_7px] [&>_.welcomeProjectActions]:[margin-top:42px]",
  welcomeSidebar:
    "welcomeSidebar [background:var(--sidebar)] [border-right:1px_solid_var(--border)] [min-height:0] [position:relative]",
  welcomeTitlebar:
    "welcomeTitlebar [align-items:center] [background:var(--card)] [border-bottom:1px_solid_var(--border)] [display:flex] [font-weight:600] [grid-row:1] [height:27px] [padding-left:84px] [user-select:none]",
  welcomeWorkspace:
    "welcomeWorkspace [background:var(--card)] [display:grid] [grid-column:1] [grid-row:2_/_-1] [grid-template-columns:225px_minmax(0,_1fr)] [height:100%] [min-height:0] [overflow:hidden]",
  workspaceTab:
    "workspaceTab [display:inline-flex] [flex:0_0_auto] [&_em]:[color:var(--destructive)] [&_em]:[font-size:15px] [&_em]:[font-style:normal] [&_em]:[line-height:1]",
} as const;
